using MDRAVA.Tests;

var tests = new (string Name, Func<Task> Run)[]
{
    ("Http1RequestParser parses a valid GET request", Sync(Http1RequestParserTests.ParsesValidGet)),
    ("Http1RequestParser rejects missing Host", Sync(Http1RequestParserTests.RejectsMissingHost)),
    ("Http1RequestParser rejects invalid Content-Length", Sync(Http1RequestParserTests.RejectsInvalidContentLength)),
    ("Http1RequestParser detects request bodies", Sync(Http1RequestParserTests.DetectsRequestBodyIndicators)),
    ("Http1RequestParser parses chunked transfer encoding", Sync(Http1RequestParserTests.ParsesChunkedTransferEncoding)),
    ("Http1RequestParser rejects conflicting Content-Length", Sync(Http1RequestParserTests.RejectsConflictingContentLength)),
    ("Http1RequestParser rejects Content-Length with Transfer-Encoding", Sync(Http1RequestParserTests.RejectsContentLengthWithTransferEncoding)),
    ("Http1RequestParser rejects unsupported Transfer-Encoding", Sync(Http1RequestParserTests.RejectsUnsupportedTransferEncoding)),
    ("Http1ResponseParser parses Content-Length response", Sync(Http1ResponseParserTests.ParsesContentLengthResponse)),
    ("Http1ResponseParser parses chunked response", Sync(Http1ResponseParserTests.ParsesChunkedResponse)),
    ("Http1ResponseParser treats HEAD response as no body", Sync(Http1ResponseParserTests.TreatsHeadResponseAsNoBody)),
    ("Http1ResponseParser treats 204 as no body", Sync(Http1ResponseParserTests.TreatsNoContentAsNoBody)),
    ("Http1ResponseParser treats 304 as no body", Sync(Http1ResponseParserTests.TreatsNotModifiedAsNoBody)),
    ("Http1ResponseParser rejects invalid Content-Length", Sync(Http1ResponseParserTests.RejectsInvalidResponseContentLength)),
    ("Header policy filters standard hop-by-hop headers", Sync(HeaderPolicyTests.FiltersStandardHopByHopHeaders)),
    ("Header policy filters Connection-nominated headers", Sync(HeaderPolicyTests.FiltersConnectionNominatedHeaders)),
    ("SingleUpstreamRouteMatcher matches wildcard route", Sync(RouteMatcherTests.MatchesWildcardRoute)),
    ("SingleUpstreamRouteMatcher matches host without request port", Sync(RouteMatcherTests.MatchesHostWithoutRequestPort)),
    ("Data directory uses configured override", Sync(ConfigurationTests.DataDirectoryUsesConfiguredOverride)),
    ("Data directory uses environment override", Sync(ConfigurationTests.DataDirectoryUsesEnvironmentOverride)),
    ("Data directory defaults under local application data when available", Sync(ConfigurationTests.DataDirectoryDefaultsUnderLocalApplicationDataWhenAvailable)),
    ("Loader loads valid per-site JSON config files", ConfigurationTests.LoaderLoadsValidSiteFiles),
    ("Loader loads equivalent JSON and YAML site files", ConfigurationTests.LoaderLoadsEquivalentJsonAndYamlSiteFiles),
    ("Loader reports YAML parse errors with per-file diagnostics", ConfigurationTests.LoaderReportsYamlParseErrorsWithPerFileDiagnostics),
    ("Loader loads route load-balancing and health-check settings", ConfigurationTests.LoaderLoadsRouteLoadBalancingAndHealthCheckSettings),
    ("Loader creates missing config directories and loads empty snapshot", ConfigurationTests.LoaderCreatesMissingConfigDirectoriesAndLoadsEmptySnapshot),
    ("Loader does not overwrite existing placeholder files", ConfigurationTests.LoaderDoesNotOverwriteExistingPlaceholderFiles),
    ("Loader loads existing empty sites directory", ConfigurationTests.LoaderLoadsExistingEmptySitesDirectory),
    ("Loader uses defaults when operational config is missing", ConfigurationTests.LoaderUsesDefaultsWhenOperationalConfigIsMissing),
    ("Loader loads explicit operational timeout settings", ConfigurationTests.LoaderLoadsExplicitOperationalTimeouts),
    ("Loader loads observability defaults", ConfigurationTests.LoaderLoadsObservabilityDefaults),
    ("Loader loads explicit observability settings", ConfigurationTests.LoaderLoadsExplicitObservabilitySettings),
    ("Loader rejects invalid observability capacity", ConfigurationTests.LoaderRejectsInvalidObservabilityCapacity),
    ("Loader loads hardening limit defaults", ConfigurationTests.LoaderLoadsLimitDefaults),
    ("Loader rejects invalid hardening limits", ConfigurationTests.LoaderRejectsInvalidLimitSettings),
    ("Loader rejects invalid operational timeout settings", ConfigurationTests.LoaderRejectsInvalidOperationalTimeouts),
    ("Loader rejects invalid tunnel connection limit", ConfigurationTests.LoaderRejectsInvalidTunnelLimit),
    ("Loader loads HTTPS listener with certificate", ConfigurationTests.LoaderLoadsHttpsListenerWithCertificate),
    ("Loader rejects HTTPS listener with missing certificate reference", ConfigurationTests.LoaderRejectsHttpsListenerWithMissingCertificateReference),
    ("Loader rejects invalid certificate path", ConfigurationTests.LoaderRejectsInvalidCertificatePath),
    ("Loader rejects invalid certificate password", ConfigurationTests.LoaderRejectsInvalidCertificatePassword),
    ("Loader rejects duplicate SNI certificate mapping", ConfigurationTests.LoaderRejectsDuplicateSniCertificateMapping),
    ("Loader merges SNI mappings from shared HTTPS listener", ConfigurationTests.LoaderMergesSniMappingsFromSharedHttpsListener),
    ("Loader rejects invalid per-site JSON config files", ConfigurationTests.LoaderRejectsInvalidSiteFile),
    ("Reload preserves active snapshot when load fails", ConfigurationTests.ReloadPreservesActiveSnapshotWhenLoadFails),
    ("Reload replaces active snapshot when load succeeds", ConfigurationTests.ReloadReplacesActiveSnapshotWhenLoadSucceeds),
    ("Reload replaces active snapshot with empty sites directory", ConfigurationTests.ReloadReplacesActiveSnapshotWithEmptySitesDirectory),
    ("Active inspection projection reflects store", ConfigurationTests.ActiveInspectionProjectionReflectsStore),
    ("Loader rejects unsafe header policy rule", ConfigurationTests.LoaderRejectsUnsafeHeaderRule),
    ("Config validate reports valid config without applying", ConfigurationTests.ConfigValidateReportsValidWithoutApplying),
    ("Config validate reports invalid config without replacing active config", ConfigurationTests.ConfigValidateReportsInvalidWithoutReplacingActiveConfig),
    ("Config normalize converts YAML to JSON without applying", ConfigurationTests.ConfigNormalizeConvertsYamlToJsonWithoutApplying),
    ("Effective config projection redacts certificate secrets", ConfigurationTests.EffectiveConfigProjectionRedactsCertificateSecrets),
    ("Reload failure reports per-file error and preserves active config", ConfigurationTests.ReloadFailureReportsPerFileErrorAndPreservesActiveConfig),
    ("Default admin bind is localhost-only", Sync(AdminSecurityTests.DefaultAdminBindIsLocalhostOnly)),
    ("Non-local admin bind without auth is rejected", Sync(AdminSecurityTests.NonLocalAdminBindWithoutAuthIsRejected)),
    ("Operational config rejects non-local admin URL without auth", Sync(AdminSecurityTests.OperationalConfigRejectsNonLocalAdminUrlWithoutAuth)),
    ("Protected admin endpoint rejects missing auth", AdminSecurityTests.ProtectedEndpointRejectsMissingAuth),
    ("Protected admin endpoint rejects wrong auth", AdminSecurityTests.ProtectedEndpointRejectsWrongAuth),
    ("Protected admin endpoint accepts valid bearer token", AdminSecurityTests.ProtectedEndpointAcceptsValidBearerToken),
    ("Sensitive admin projections redact configured secrets", Sync(AdminSecurityTests.SensitiveProjectionRedactsConfiguredAdminSecrets)),
    ("Effective config does not expose admin token", Sync(AdminSecurityTests.EffectiveConfigDoesNotExposeAdminToken)),
    ("Generated placeholder config does not contain real secret", Sync(AdminSecurityTests.GeneratedPlaceholderConfigDoesNotContainRealSecret)),
    ("Admin audit does not log token values", AdminSecurityTests.AdminAuditDoesNotLogTokenValues),
    ("Manual PFX certificate behavior remains valid", AcmeTests.ManualPfxCertificateBehaviorRemainsValid),
    ("ACME config validation rejects missing terms acceptance", Sync(AcmeTests.AcmeConfigValidationRejectsMissingTermsAcceptance)),
    ("HTTP-01 challenge returns exact token response", Sync(AcmeTests.Http01ChallengeReturnsExactTokenResponse)),
    ("Unknown HTTP-01 challenge returns safe 404", Sync(AcmeTests.UnknownHttp01ChallengeReturnsSafe404)),
    ("ACME renewal stores material under certs directory", AcmeTests.AcmeRenewalStoresMaterialUnderCertsDirectory),
    ("Loader loads stored ACME certificate on startup", AcmeTests.LoaderLoadsStoredAcmeCertificateOnStartup),
    ("Failed ACME renewal preserves current active certificate", AcmeTests.FailedAcmeRenewalPreservesCurrentActiveCertificate),
    ("ACME status projection does not expose private material", AcmeTests.AcmeStatusProjectionDoesNotExposePrivateMaterial),
    ("ACME renewal avoids tight retry loop after failure", AcmeTests.AcmeRenewalAvoidsTightRetryLoopAfterFailure),
    ("Existing HTTP upstream config remains valid", UpstreamTlsTests.ExistingHttpUpstreamConfigRemainsValid),
    ("HTTPS upstream config parses and validates", UpstreamTlsTests.HttpsUpstreamConfigParsesAndValidates),
    ("Unsupported upstream scheme is rejected", UpstreamTlsTests.UnsupportedUpstreamSchemeIsRejected),
    ("Ambiguous upstream address is rejected", UpstreamTlsTests.AmbiguousUpstreamAddressIsRejected),
    ("Upstream pool key differs for HTTP and HTTPS", Sync(UpstreamTlsTests.PoolKeyDiffersForHttpAndHttps)),
    ("Upstream pool key differs for SNI and validation", Sync(UpstreamTlsTests.PoolKeyDiffersForDifferentSniAndValidation)),
    ("HTTPS upstream uses SslStream path", UpstreamTlsTests.HttpsUpstreamUsesSslStreamPath),
    ("HTTPS upstream proxy forwards through TLS", UpstreamTlsTests.HttpsUpstreamProxyForwardsThroughTls),
    ("HTTPS health checks use TLS settings", UpstreamTlsTests.HttpsHealthChecksUseTlsSettings),
    ("Upstream certificate validation is enabled by default", UpstreamTlsTests.CertificateValidationIsEnabledByDefault),
    ("Explicit unsafe upstream validation projects as unsafe", UpstreamTlsTests.ExplicitUnsafeValidationModeIsProjectedAsUnsafe),
    ("TLS validation failure does not fall back to plaintext", UpstreamTlsTests.TlsValidationFailureDoesNotFallBackToPlaintext),
    ("Caching disabled by default", CacheTests.CachingDisabledByDefault),
    ("Disabled cache keeps existing proxy behavior", CacheTests.DisabledCacheKeepsExistingProxyBehavior),
    ("Invalid cache policy is rejected", Sync(CacheTests.InvalidCachePolicyIsRejected)),
    ("Enabled GET 200 response is stored and served", CacheTests.EnabledGet200ResponseIsStoredAndServed),
    ("HEAD cached response returns headers without body", CacheTests.HeadResponseReturnsHeadersWithoutBody),
    ("Query string is part of cache key", Sync(CacheTests.QueryStringIsPartOfCacheKey)),
    ("Host and vary headers affect cache key", Sync(CacheTests.HostAndVaryHeadersAffectCacheKey)),
    ("Authorization request is not cached by default", Sync(CacheTests.AuthorizationRequestIsNotCachedByDefault)),
    ("Set-Cookie response is not cached by default", Sync(CacheTests.SetCookieResponseIsNotCachedByDefault)),
    ("Cache-Control no-store is not cached", Sync(CacheTests.NoStoreResponseIsNotCached)),
    ("Cache-Control private is not cached by default", Sync(CacheTests.PrivateResponseIsNotCachedByDefault)),
    ("Cache-Control max-age controls TTL and expiry", Sync(CacheTests.MaxAgeControlsTtlAndExpiredEntryIsNotServed)),
    ("Oversized response is streamed but not cached", CacheTests.OversizedResponseIsStreamedButNotCached),
    ("Hop-by-hop cache headers are not stored", Sync(CacheTests.HopByHopHeadersAndTransferEncodingAreNotStored)),
    ("Cache clear endpoint clears entries", CacheTests.CacheClearEndpointClearsEntries),
    ("Cache clear endpoint is protected", CacheTests.CacheClearEndpointIsProtected),
    ("Successful config reload clears cache", CacheTests.SuccessfulReloadClearsCache),
    ("Failed config reload does not clear cache", CacheTests.FailedReloadDoesNotClearCache),
    ("Host startup succeeds from fresh data directory", StartupSmokeTests.StartsFromFreshDataDirectory),
    ("Host startup fails when existing site config is invalid", StartupSmokeTests.FailsStartupWhenExistingSiteConfigIsInvalid),
    ("Host startup succeeds with valid site config", StartupSmokeTests.StartsWithValidSiteConfig),
    ("Proxy dataplane proxies one GET request end to end", ProxyIntegrationTests.ProxiesSingleGetToUpstream),
    ("Proxy dataplane proxies fixed-length request and response", ProxyIntegrationTests.ProxiesFixedLengthRequestAndResponse),
    ("Proxy dataplane proxies chunked request and response", ProxyIntegrationTests.ProxiesChunkedRequestAndResponse),
    ("Proxy dataplane does not relay HEAD response body", ProxyIntegrationTests.DoesNotRelayHeadResponseBody),
    ("Proxy dataplane proxies 204 without response body", ProxyIntegrationTests.ProxiesNoContentWithoutBody),
    ("Proxy dataplane proxies 304 without response body", ProxyIntegrationTests.ProxiesNotModifiedWithoutBody),
    ("Proxy dataplane rejects invalid request framing", ProxyIntegrationTests.RejectsInvalidRequestFraming),
    ("Proxy dataplane rejects malformed chunked request body", ProxyIntegrationTests.RejectsMalformedChunkedRequestBody),
    ("Proxy dataplane filters hop-by-hop request headers", ProxyIntegrationTests.FiltersHopByHopRequestHeaders),
    ("Proxy dataplane preserves Host header", ProxyIntegrationTests.PreservesHostHeader),
    ("Proxy dataplane emits generated response request ID", ProxyIntegrationTests.ResponseIncludesGeneratedRequestId),
    ("Proxy dataplane preserves external request ID in diagnostics", ProxyIntegrationTests.ExternalRequestIdIsPreservedInDiagnostics),
    ("Proxy dataplane records successful diagnostics", ProxyIntegrationTests.SuccessfulRequestProducesDiagnosticRouteAndUpstream),
    ("Proxy dataplane records upstream connect failure diagnostics", ProxyIntegrationTests.UpstreamConnectFailureProducesDiagnosticClassification),
    ("Proxy dataplane can disable access logs while keeping diagnostics", ProxyIntegrationTests.AccessLoggingCanBeDisabledWhileDiagnosticsRemainEnabled),
    ("HTTP to HTTPS redirect preserves path and query", ProxyIntegrationTests.HttpToHttpsRedirectPreservesPathAndQuery),
    ("Canonical host redirect works", ProxyIntegrationTests.CanonicalHostRedirectWorks),
    ("Canonical host redirect does not loop", ProxyIntegrationTests.CanonicalHostRedirectDoesNotLoop),
    ("Forwarded headers generated for untrusted direct client", ProxyIntegrationTests.ForwardedHeadersGeneratedForUntrustedDirectClient),
    ("Trusted proxy accepts prior forwarded chain", ProxyIntegrationTests.TrustedProxyAcceptsPriorForwardedChain),
    ("Untrusted client forwarded headers are stripped and replaced", ProxyIntegrationTests.UntrustedClientForwardedHeadersAreStrippedAndReplaced),
    ("Request header set/remove rules apply upstream", ProxyIntegrationTests.RequestHeaderSetAndRemoveRulesApplyUpstream),
    ("Response header set/remove rules apply downstream", ProxyIntegrationTests.ResponseHeaderSetAndRemoveRulesApplyDownstream),
    ("Path prefix stripping preserves query string", ProxyIntegrationTests.PathPrefixStrippingPreservesQueryString),
    ("Path prefix replacement works", ProxyIntegrationTests.PathPrefixReplacementWorks),
    ("Path rewrite no-match forwards original target", ProxyIntegrationTests.PathRewriteNoMatchForwardsOriginalTarget),
    ("Redirect route returns configured redirect", ProxyIntegrationTests.RedirectRouteReturnsConfiguredRedirect),
    ("Static response route returns configured response", ProxyIntegrationTests.StaticResponseRouteReturnsConfiguredResponse),
    ("Maintenance mode returns 503 and does not contact upstream", ProxyIntegrationTests.MaintenanceModeReturns503AndDoesNotContactUpstream),
    ("Per-route body-size override works", ProxyIntegrationTests.PerRouteBodySizeOverrideWorks),
    ("Per-route access-log disable is reflected in diagnostics", ProxyIntegrationTests.PerRouteAccessLogDisableIsReflectedInDiagnostics),
    ("Proxy dataplane records no-route diagnostics and status summary", ProxyIntegrationTests.NoMatchingRouteProducesDiagnosticClassification),
    ("Proxy dataplane rejects oversized request head", ProxyIntegrationTests.OversizedRequestHeadIsRejected),
    ("Proxy dataplane rejects excessive header count", ProxyIntegrationTests.ExcessiveHeaderCountIsRejected),
    ("Proxy dataplane rejects excessive header line", ProxyIntegrationTests.ExcessiveHeaderLineIsRejected),
    ("Proxy dataplane rejects excessive request body size", ProxyIntegrationTests.ExcessiveRequestBodySizeIsRejected),
    ("Proxy dataplane rejects oversized chunked request body", ProxyIntegrationTests.ChunkedRequestBodySizeIsRejected),
    ("Proxy dataplane enforces per-IP request rate limit", ProxyIntegrationTests.PerIpRequestRateLimitIsEnforced),
    ("Proxy dataplane times out incomplete request head", ProxyIntegrationTests.TimesOutIncompleteRequestHead),
    ("Proxy dataplane times out incomplete Content-Length request body", ProxyIntegrationTests.TimesOutIncompleteContentLengthRequestBody),
    ("Proxy dataplane times out incomplete chunked request body", ProxyIntegrationTests.TimesOutIncompleteChunkedRequestBody),
    ("Proxy dataplane maps unavailable upstream to 502", ProxyIntegrationTests.UnavailableUpstreamProducesBadGateway),
    ("Proxy dataplane maps upstream response-head timeout to 504", ProxyIntegrationTests.UpstreamResponseHeadTimeoutProducesGatewayTimeout),
    ("Proxy dataplane closes after started response on upstream early close", ProxyIntegrationTests.UpstreamContentLengthEarlyCloseClosesAfterStartedResponse),
    ("HTTPS listener proxies GET to upstream", ProxyIntegrationTests.HttpsListenerProxiesGetToUpstream),
    ("HTTPS listener selects certificate by SNI", ProxyIntegrationTests.HttpsListenerSelectsCertificateBySni),
    ("HTTPS listener uses default certificate for unmatched SNI", ProxyIntegrationTests.HttpsListenerUsesDefaultCertificateForUnmatchedSni),
    ("HTTPS listener uses default certificate without SNI", ProxyIntegrationTests.HttpsListenerUsesDefaultCertificateWithoutSni),
    ("HTTPS listener fails handshake when no certificate matches", ProxyIntegrationTests.HttpsListenerFailsHandshakeWhenNoCertificateMatches),
    ("HTTPS listener times out incomplete TLS handshake", ProxyIntegrationTests.HttpsListenerTimesOutIncompleteTlsHandshake),
    ("Persistent client processes two sequential GETs and reuses upstream", ProxyIntegrationTests.PersistentClientProcessesTwoSequentialGetsAndReusesUpstream),
    ("Client Connection close header closes after response", ProxyIntegrationTests.ClientConnectionCloseHeaderClosesAfterResponse),
    ("HTTP/1.0 client closes by default", ProxyIntegrationTests.Http10ClientClosesByDefault),
    ("Max requests per client connection is enforced", ProxyIntegrationTests.MaxRequestsPerClientConnectionIsEnforced),
    ("Client keep-alive idle timeout closes connection", ProxyIntegrationTests.ClientKeepAliveIdleTimeoutClosesConnection),
    ("Malformed second request closes connection", ProxyIntegrationTests.MalformedSecondRequestClosesConnection),
    ("Persistent client proxies Content-Length POST", ProxyIntegrationTests.PersistentClientProxiesContentLengthPost),
    ("Persistent client proxies chunked POST", ProxyIntegrationTests.PersistentClientProxiesChunkedPost),
    ("Upstream connection is not reused after response Connection close", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterResponseConnectionClose),
    ("Upstream connection is not reused after premature disconnect", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterPrematureDisconnect),
    ("Upstream connection is not reused after framing error", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterFramingError),
    ("WebSocket Upgrade over plaintext returns 101", ProxyIntegrationTests.WebSocketUpgradeOverPlaintextReturnsSwitchingProtocols),
    ("WebSocket Upgrade produces tunnel diagnostic", ProxyIntegrationTests.WebSocketUpgradeProducesTunnelDiagnostic),
    ("WebSocket tunnel relays client bytes upstream", ProxyIntegrationTests.WebSocketTunnelRelaysClientBytesToUpstream),
    ("WebSocket tunnel relays upstream bytes client", ProxyIntegrationTests.WebSocketTunnelRelaysUpstreamBytesToClient),
    ("WebSocket tunnel closes when client closes", ProxyIntegrationTests.WebSocketTunnelClosesWhenClientCloses),
    ("WebSocket tunnel closes when upstream closes", ProxyIntegrationTests.WebSocketTunnelClosesWhenUpstreamCloses),
    ("WebSocket tunnel idle timeout closes tunnel", ProxyIntegrationTests.WebSocketTunnelIdleTimeoutClosesTunnel),
    ("WebSocket Upgrade over HTTPS returns 101", ProxyIntegrationTests.WebSocketUpgradeOverHttpsReturnsSwitchingProtocols),
    ("Upgrade does not use normal upstream pool", ProxyIntegrationTests.UpgradeDoesNotUseNormalUpstreamPool),
    ("Missing WebSocket headers are rejected", ProxyIntegrationTests.MissingWebSocketHeadersAreRejected),
    ("Upstream non-101 Upgrade response is forwarded and closed", ProxyIntegrationTests.UpstreamNon101UpgradeResponseIsForwardedAndClosed),
    ("Malformed 101 Upgrade response produces bad gateway", ProxyIntegrationTests.MalformedSwitchingProtocolsResponseProducesBadGateway),
    ("Health check 2xx response is healthy", HealthCheckTests.HealthCheck2xxIsHealthy),
    ("Health check 3xx response is healthy", HealthCheckTests.HealthCheck3xxIsHealthy),
    ("Health check 4xx response is unhealthy", HealthCheckTests.HealthCheck4xxIsUnhealthy),
    ("Health check 5xx response is unhealthy", HealthCheckTests.HealthCheck5xxIsUnhealthy),
    ("Health check timeout is unhealthy", HealthCheckTests.HealthCheckTimeoutIsUnhealthy),
    ("Health state transitions to unhealthy after threshold", Sync(HealthCheckTests.HealthStateTransitionsToUnhealthyAfterThreshold)),
    ("Health state transitions to healthy after recovery threshold", Sync(HealthCheckTests.HealthStateTransitionsToHealthyAfterRecoveryThreshold)),
    ("Round-robin distributes sequential requests across two upstreams", ProxyIntegrationTests.RoundRobinDistributesSequentialRequestsAcrossTwoUpstreams),
    ("Unhealthy upstream is not selected", ProxyIntegrationTests.UnhealthyUpstreamIsNotSelected),
    ("All unhealthy upstreams return service unavailable", ProxyIntegrationTests.AllUnhealthyUpstreamsReturnServiceUnavailable),
    ("WebSocket Upgrade uses round-robin upstream selection", ProxyIntegrationTests.WebSocketUpgradeUsesRoundRobinUpstreamSelection),
    ("Upstream pool uses distinct endpoint keys", ProxyIntegrationTests.UpstreamPoolUsesDistinctEndpointKeys),
    ("Recent diagnostics store is bounded", Sync(ObservabilityTests.RecentDiagnosticsStoreIsBounded)),
    ("Diagnostics controller honors safe limit", Sync(ObservabilityTests.DiagnosticsControllerHonorsSafeLimit)),
    ("Diagnostics event omits bodies and secrets", Sync(ObservabilityTests.DiagnosticsEventDoesNotCarryBodiesOrSecrets)),
    ("Admission controller enforces client limit", Sync(HardeningTests.AdmissionControllerEnforcesClientLimit)),
    ("Admission controller enforces TLS handshake limit", Sync(HardeningTests.AdmissionControllerEnforcesTlsHandshakeLimit)),
    ("Rate limiter enforces request limit and refill", Sync(HardeningTests.RateLimiterEnforcesRequestLimitAndRefills)),
    ("Rate limiter enforces upgrade limit", Sync(HardeningTests.RateLimiterEnforcesUpgradeLimit)),
    ("Rate limiter cleans stale entries", Sync(HardeningTests.RateLimiterCleansStaleEntries)),
    ("Shutdown coordinator exposes grace deadline", Sync(HardeningTests.ShutdownCoordinatorExposesGraceDeadlineAndCancels))
};

var failures = 0;

foreach (var test in tests)
{
    try
    {
        await test.Run();
        Console.WriteLine($"PASS {test.Name}");
    }
    catch (Exception exception)
    {
        failures++;
        Console.Error.WriteLine($"FAIL {test.Name}");
        Console.Error.WriteLine(exception);
    }
}

if (failures > 0)
{
    Environment.ExitCode = 1;
    return;
}

Console.WriteLine($"Passed {tests.Length} tests.");

static Func<Task> Sync(Action test)
{
    return () =>
    {
        test();
        return Task.CompletedTask;
    };
}
