using MDRAVA.Tests;

var tests = new (string Name, Func<Task> Run)[]
{
    ("Http1RequestParser parses a valid GET request", Sync(Http1RequestParserTests.ParsesValidGet)),
    ("Http1RequestParser rejects missing Host", Sync(Http1RequestParserTests.RejectsMissingHost)),
    ("Http1RequestParser rejects invalid Content-Length", Sync(Http1RequestParserTests.RejectsInvalidContentLength)),
    ("Http1RequestParser detects request bodies", Sync(Http1RequestParserTests.DetectsRequestBodyIndicators)),
    ("Http1RequestParser parses chunked transfer encoding", Sync(Http1RequestParserTests.ParsesChunkedTransferEncoding)),
    ("Http1RequestParser rejects conflicting Content-Length", Sync(Http1RequestParserTests.RejectsConflictingContentLength)),
    ("Http1RequestParser rejects Content-Length with Transfer-Encoding", Sync(Http1RequestParserTests.RejectsContentLengthWithTransferEncoding)),
    ("Http1RequestParser rejects unsupported Transfer-Encoding", Sync(Http1RequestParserTests.RejectsUnsupportedTransferEncoding)),
    ("Http1ResponseParser parses Content-Length response", Sync(Http1ResponseParserTests.ParsesContentLengthResponse)),
    ("Http1ResponseParser parses chunked response", Sync(Http1ResponseParserTests.ParsesChunkedResponse)),
    ("Http1ResponseParser treats HEAD response as no body", Sync(Http1ResponseParserTests.TreatsHeadResponseAsNoBody)),
    ("Http1ResponseParser treats 204 as no body", Sync(Http1ResponseParserTests.TreatsNoContentAsNoBody)),
    ("Http1ResponseParser treats 304 as no body", Sync(Http1ResponseParserTests.TreatsNotModifiedAsNoBody)),
    ("Http1ResponseParser rejects invalid Content-Length", Sync(Http1ResponseParserTests.RejectsInvalidResponseContentLength)),
    ("Header policy filters standard hop-by-hop headers", Sync(HeaderPolicyTests.FiltersStandardHopByHopHeaders)),
    ("Header policy filters Connection-nominated headers", Sync(HeaderPolicyTests.FiltersConnectionNominatedHeaders)),
    ("SingleUpstreamRouteMatcher matches wildcard route", Sync(RouteMatcherTests.MatchesWildcardRoute)),
    ("SingleUpstreamRouteMatcher matches host without request port", Sync(RouteMatcherTests.MatchesHostWithoutRequestPort)),
    ("Data directory uses configured override", Sync(ConfigurationTests.DataDirectoryUsesConfiguredOverride)),
    ("Data directory uses environment override", Sync(ConfigurationTests.DataDirectoryUsesEnvironmentOverride)),
    ("Data directory defaults under local application data when available", Sync(ConfigurationTests.DataDirectoryDefaultsUnderLocalApplicationDataWhenAvailable)),
    ("Loader loads valid per-site JSON config files", ConfigurationTests.LoaderLoadsValidSiteFiles),
    ("Loader loads equivalent JSON and YAML site files", ConfigurationTests.LoaderLoadsEquivalentJsonAndYamlSiteFiles),
    ("Loader reports YAML parse errors with per-file diagnostics", ConfigurationTests.LoaderReportsYamlParseErrorsWithPerFileDiagnostics),
    ("Loader loads route load-balancing and health-check settings", ConfigurationTests.LoaderLoadsRouteLoadBalancingAndHealthCheckSettings),
    ("Loader creates missing config directories and loads empty snapshot", ConfigurationTests.LoaderCreatesMissingConfigDirectoriesAndLoadsEmptySnapshot),
    ("Loader does not overwrite existing placeholder files", ConfigurationTests.LoaderDoesNotOverwriteExistingPlaceholderFiles),
    ("Loader loads existing empty sites directory", ConfigurationTests.LoaderLoadsExistingEmptySitesDirectory),
    ("Loader uses defaults when operational config is missing", ConfigurationTests.LoaderUsesDefaultsWhenOperationalConfigIsMissing),
    ("Loader loads explicit operational timeout settings", ConfigurationTests.LoaderLoadsExplicitOperationalTimeouts),
    ("Loader loads observability defaults", ConfigurationTests.LoaderLoadsObservabilityDefaults),
    ("Loader loads explicit observability settings", ConfigurationTests.LoaderLoadsExplicitObservabilitySettings),
    ("Loader rejects invalid observability capacity", ConfigurationTests.LoaderRejectsInvalidObservabilityCapacity),
    ("Loader loads hardening limit defaults", ConfigurationTests.LoaderLoadsLimitDefaults),
    ("Loader rejects invalid hardening limits", ConfigurationTests.LoaderRejectsInvalidLimitSettings),
    ("Loader rejects invalid operational timeout settings", ConfigurationTests.LoaderRejectsInvalidOperationalTimeouts),
    ("Loader rejects invalid tunnel connection limit", ConfigurationTests.LoaderRejectsInvalidTunnelLimit),
    ("Loader loads HTTPS listener with certificate", ConfigurationTests.LoaderLoadsHttpsListenerWithCertificate),
    ("Loader rejects HTTPS listener with missing certificate reference", ConfigurationTests.LoaderRejectsHttpsListenerWithMissingCertificateReference),
    ("Loader rejects invalid certificate path", ConfigurationTests.LoaderRejectsInvalidCertificatePath),
    ("Loader rejects invalid certificate password", ConfigurationTests.LoaderRejectsInvalidCertificatePassword),
    ("Loader rejects duplicate SNI certificate mapping", ConfigurationTests.LoaderRejectsDuplicateSniCertificateMapping),
    ("Loader merges SNI mappings from shared HTTPS listener", ConfigurationTests.LoaderMergesSniMappingsFromSharedHttpsListener),
    ("Loader rejects invalid per-site JSON config files", ConfigurationTests.LoaderRejectsInvalidSiteFile),
    ("Reload preserves active snapshot when load fails", ConfigurationTests.ReloadPreservesActiveSnapshotWhenLoadFails),
    ("Reload replaces active snapshot when load succeeds", ConfigurationTests.ReloadReplacesActiveSnapshotWhenLoadSucceeds),
    ("Reload replaces active snapshot with empty sites directory", ConfigurationTests.ReloadReplacesActiveSnapshotWithEmptySitesDirectory),
    ("Active inspection projection reflects store", ConfigurationTests.ActiveInspectionProjectionReflectsStore),
    ("Loader rejects unsafe header policy rule", ConfigurationTests.LoaderRejectsUnsafeHeaderRule),
    ("Config validate reports valid config without applying", ConfigurationTests.ConfigValidateReportsValidWithoutApplying),
    ("Config validate reports invalid config without replacing active config", ConfigurationTests.ConfigValidateReportsInvalidWithoutReplacingActiveConfig),
    ("Config normalize converts YAML to JSON without applying", ConfigurationTests.ConfigNormalizeConvertsYamlToJsonWithoutApplying),
    ("Effective config projection redacts certificate secrets", ConfigurationTests.EffectiveConfigProjectionRedactsCertificateSecrets),
    ("Reload failure reports per-file error and preserves active config", ConfigurationTests.ReloadFailureReportsPerFileErrorAndPreservesActiveConfig),
    ("Default admin bind is localhost-only", Sync(AdminSecurityTests.DefaultAdminBindIsLocalhostOnly)),
    ("Non-local admin bind without auth is rejected", Sync(AdminSecurityTests.NonLocalAdminBindWithoutAuthIsRejected)),
    ("Operational config rejects non-local admin URL without auth", Sync(AdminSecurityTests.OperationalConfigRejectsNonLocalAdminUrlWithoutAuth)),
    ("Protected admin endpoint rejects missing auth", AdminSecurityTests.ProtectedEndpointRejectsMissingAuth),
    ("Protected admin endpoint rejects wrong auth", AdminSecurityTests.ProtectedEndpointRejectsWrongAuth),
    ("Protected admin endpoint accepts valid bearer token", AdminSecurityTests.ProtectedEndpointAcceptsValidBearerToken),
    ("Sensitive admin projections redact configured secrets", Sync(AdminSecurityTests.SensitiveProjectionRedactsConfiguredAdminSecrets)),
    ("Effective config does not expose admin token", Sync(AdminSecurityTests.EffectiveConfigDoesNotExposeAdminToken)),
    ("Generated placeholder config does not contain real secret", Sync(AdminSecurityTests.GeneratedPlaceholderConfigDoesNotContainRealSecret)),
    ("Admin audit does not log token values", AdminSecurityTests.AdminAuditDoesNotLogTokenValues),
    ("Manual PFX certificate behavior remains valid", AcmeTests.ManualPfxCertificateBehaviorRemainsValid),
    ("ACME config validation rejects missing terms acceptance", Sync(AcmeTests.AcmeConfigValidationRejectsMissingTermsAcceptance)),
    ("HTTP-01 challenge returns exact token response", Sync(AcmeTests.Http01ChallengeReturnsExactTokenResponse)),
    ("Unknown HTTP-01 challenge returns safe 404", Sync(AcmeTests.UnknownHttp01ChallengeReturnsSafe404)),
    ("ACME renewal stores material under certs directory", AcmeTests.AcmeRenewalStoresMaterialUnderCertsDirectory),
    ("Loader loads stored ACME certificate on startup", AcmeTests.LoaderLoadsStoredAcmeCertificateOnStartup),
    ("Failed ACME renewal preserves current active certificate", AcmeTests.FailedAcmeRenewalPreservesCurrentActiveCertificate),
    ("ACME status projection does not expose private material", AcmeTests.AcmeStatusProjectionDoesNotExposePrivateMaterial),
    ("ACME renewal avoids tight retry loop after failure", AcmeTests.AcmeRenewalAvoidsTightRetryLoopAfterFailure),
    ("Existing HTTP upstream config remains valid", UpstreamTlsTests.ExistingHttpUpstreamConfigRemainsValid),
    ("HTTPS upstream config parses and validates", UpstreamTlsTests.HttpsUpstreamConfigParsesAndValidates),
    ("Unsupported upstream scheme is rejected", UpstreamTlsTests.UnsupportedUpstreamSchemeIsRejected),
    ("Ambiguous upstream address is rejected", UpstreamTlsTests.AmbiguousUpstreamAddressIsRejected),
    ("Upstream pool key differs for HTTP and HTTPS", Sync(UpstreamTlsTests.PoolKeyDiffersForHttpAndHttps)),
    ("Upstream pool key differs for SNI and validation", Sync(UpstreamTlsTests.PoolKeyDiffersForDifferentSniAndValidation)),
    ("HTTPS upstream uses SslStream path", UpstreamTlsTests.HttpsUpstreamUsesSslStreamPath),
    ("HTTPS upstream proxy forwards through TLS", UpstreamTlsTests.HttpsUpstreamProxyForwardsThroughTls),
    ("HTTPS health checks use TLS settings", UpstreamTlsTests.HttpsHealthChecksUseTlsSettings),
    ("Upstream certificate validation is enabled by default", UpstreamTlsTests.CertificateValidationIsEnabledByDefault),
    ("Explicit unsafe upstream validation projects as unsafe", UpstreamTlsTests.ExplicitUnsafeValidationModeIsProjectedAsUnsafe),
    ("TLS validation failure does not fall back to plaintext", UpstreamTlsTests.TlsValidationFailureDoesNotFallBackToPlaintext),
    ("Caching disabled by default", CacheTests.CachingDisabledByDefault),
    ("Disabled cache keeps existing proxy behavior", CacheTests.DisabledCacheKeepsExistingProxyBehavior),
    ("Invalid cache policy is rejected", Sync(CacheTests.InvalidCachePolicyIsRejected)),
    ("Enabled GET 200 response is stored and served", CacheTests.EnabledGet200ResponseIsStoredAndServed),
    ("HEAD cached response returns headers without body", CacheTests.HeadResponseReturnsHeadersWithoutBody),
    ("Query string is part of cache key", Sync(CacheTests.QueryStringIsPartOfCacheKey)),
    ("Host and vary headers affect cache key", Sync(CacheTests.HostAndVaryHeadersAffectCacheKey)),
    ("Authorization request is not cached by default", Sync(CacheTests.AuthorizationRequestIsNotCachedByDefault)),
    ("Set-Cookie response is not cached by default", Sync(CacheTests.SetCookieResponseIsNotCachedByDefault)),
    ("Cache-Control no-store is not cached", Sync(CacheTests.NoStoreResponseIsNotCached)),
    ("Cache-Control private is not cached by default", Sync(CacheTests.PrivateResponseIsNotCachedByDefault)),
    ("Cache-Control max-age controls TTL and expiry", Sync(CacheTests.MaxAgeControlsTtlAndExpiredEntryIsNotServed)),
    ("Oversized response is streamed but not cached", CacheTests.OversizedResponseIsStreamedButNotCached),
    ("Hop-by-hop cache headers are not stored", Sync(CacheTests.HopByHopHeadersAndTransferEncodingAreNotStored)),
    ("Cache clear endpoint clears entries", CacheTests.CacheClearEndpointClearsEntries),
    ("Cache clear endpoint is protected", CacheTests.CacheClearEndpointIsProtected),
    ("Successful config reload clears cache", CacheTests.SuccessfulReloadClearsCache),
    ("Failed config reload does not clear cache", CacheTests.FailedReloadDoesNotClearCache),
    ("Metrics endpoint is protected by admin auth", MetricsTests.MetricsEndpointIsProtectedByAdminAuth),
    ("Metrics endpoint returns Prometheus text", Sync(MetricsTests.MetricsEndpointReturnsPrometheusText)),
    ("Metrics include request counters after proxied request", MetricsTests.MetricsIncludeRequestCountersAfterProxiedRequest),
    ("Metrics include cache counters after cache activity", Sync(MetricsTests.MetricsIncludeCacheCountersAfterCacheActivity)),
    ("Metrics include reload success and failure counters", MetricsTests.MetricsIncludeReloadCounters),
    ("Metrics do not expose raw request details", MetricsTests.MetricsDoNotExposeRawRequestDetails),
    ("Public metrics exposure is disabled by default", Sync(MetricsTests.PublicMetricsExposureIsDisabledByDefault)),
    ("Invalid metrics config is rejected", Sync(MetricsTests.InvalidMetricsConfigIsRejected)),
    ("Metric labels are bounded and sanitized", Sync(MetricsTests.MetricLabelsAreBoundedAndSanitized)),
    ("Route dry-run matches dataplane matcher", Sync(RouteDiagnosticsTests.DryRunMatchesSameRouteAsDataplaneMatcher)),
    ("Route dry-run has no upstream I/O or retry circuit cache mutation", Sync(RouteDiagnosticsTests.DryRunDoesNotPerformUpstreamIoOrMutateRetryCircuitOrCacheState)),
    ("Route dry-run reports no-match reason", Sync(RouteDiagnosticsTests.DryRunReportsNoMatchReason)),
    ("Route dry-run reports path rewrite result", Sync(RouteDiagnosticsTests.DryRunReportsPathRewriteResult)),
    ("Route dry-run can select HTTP/3 protocol listener", Sync(RouteDiagnosticsTests.DryRunCanSelectHttp3ProtocolListener)),
    ("Route dry-run reports generated route actions", Sync(RouteDiagnosticsTests.DryRunReportsGeneratedRouteActions)),
    ("Route dry-run redacts sensitive headers", Sync(RouteDiagnosticsTests.DryRunRedactsSensitiveHeaders)),
    ("Config lint detects route shadowing and broad catch-all", Sync(RouteDiagnosticsTests.LintDetectsRouteShadowingAndBroadCatchAll)),
    ("Config lint detects canonical redirect loop", Sync(RouteDiagnosticsTests.LintDetectsCanonicalRedirectLoop)),
    ("Config lint detects HTTPS redirect without HTTPS listener", Sync(RouteDiagnosticsTests.LintDetectsHttpsRedirectWithoutHttpsListener)),
    ("Config lint warns about unsafe upstream TLS validation", Sync(RouteDiagnosticsTests.LintWarnsAboutUnsafeUpstreamTlsValidation)),
    ("Config lint handles JSON and YAML submitted config without applying", Sync(RouteDiagnosticsTests.LintHandlesJsonAndYamlSubmittedConfigWithoutApplying)),
    ("Config lint output has stable codes and severities", Sync(RouteDiagnosticsTests.LintOutputHasStableCodesAndSeverities)),
    ("Diagnostic endpoints require admin auth", RouteDiagnosticsTests.DiagnosticEndpointsRequireAdminAuth),
    ("Metrics include lint and route dry-run counters", Sync(RouteDiagnosticsTests.MetricsIncludeLintAndRouteDryRunCounters)),
    ("Route-only reload does not rebind unchanged listener", ListenerRebindingTests.RouteOnlyReloadDoesNotRebindUnchangedListener),
    ("Adding listener starts only new listener", ListenerRebindingTests.AddingListenerStartsOnlyNewListener),
    ("Removing listener stops accepting new connections", ListenerRebindingTests.RemovingListenerStopsAcceptingNewConnections),
    ("Changed listener is replaced safely", ListenerRebindingTests.ChangedListenerIsReplacedSafely),
    ("Failed new listener start preserves old active listener", ListenerRebindingTests.FailedNewListenerStartPreservesOldActiveListener),
    ("Failed config reload preserves old active listeners", ListenerRebindingTests.FailedConfigReloadPreservesOldActiveListeners),
    ("Certificate-only update does not rebind listener", ListenerRebindingTests.CertificateOnlyUpdateDoesNotRebindListener),
    ("Admin bind is not affected by proxy listener reload", ListenerRebindingTests.AdminBindIsNotAffectedByProxyListenerReload),
    ("Reload diagnostics report listener diff", ListenerRebindingTests.ReloadDiagnosticsReportListenerDiff),
    ("Metrics count listener reload outcomes", ListenerRebindingTests.MetricsCountListenerReloadOutcomes),
    ("HTTP/2 client preserves HTTP/1.1 behavior", ClientHttp2Tests.ExistingHttp1BehaviorRemainsUnchanged),
    ("HTTP/2 plaintext listener is rejected", Sync(ClientHttp2Tests.PlaintextHttp2ListenerIsRejected)),
    ("HTTP/2 ALPN selects h2 when enabled", ClientHttp2Tests.AlpnSelectsHttp2WhenEnabled),
    ("HTTP/2 request maps to route matcher", ClientHttp2Tests.Http2RequestMapsToRouteMatcher),
    ("HTTP/2 authority maps to host routing", ClientHttp2Tests.AuthorityMapsToHostRouting),
    ("HTTP/2 query string is preserved", ClientHttp2Tests.QueryStringIsPreserved),
    ("HTTP/2 invalid pseudo headers are rejected", ClientHttp2Tests.InvalidPseudoHeadersAreRejected),
    ("HTTP/2 forbidden connection headers are rejected", ClientHttp2Tests.ForbiddenConnectionHeadersAreRejected),
    ("HTTP/2 Huffman request header values are decoded", ClientHttp2Tests.HuffmanRequestHeaderValuesAreDecoded),
    ("HTTP/2 response omits hop-by-hop headers", ClientHttp2Tests.ResponseOmitsHopByHopHeaders),
    ("HTTP/2 static response route works", ClientHttp2Tests.StaticResponseRouteWorksOverHttp2),
    ("HTTP/2 redirect route works", ClientHttp2Tests.RedirectRouteWorksOverHttp2),
    ("HTTP/2 maintenance route works", ClientHttp2Tests.MaintenanceRouteWorksOverHttp2),
    ("HTTP/2 HEAD returns no body", ClientHttp2Tests.HeadReturnsHeadersWithoutBody),
    ("HTTP/2 cache works", ClientHttp2Tests.CacheWorksOverHttp2),
    ("HTTP/2 retry works for proxy requests", ClientHttp2Tests.RetryWorksForHttp2ProxyRequests),
    ("HTTP/2 extended CONNECT is rejected", ClientHttp2Tests.ExtendedConnectIsRejected),
    ("HTTP/2 metrics include counters", ClientHttp2Tests.MetricsIncludeHttp2Counters),
    ("Upstream HTTP/2 preserves HTTP/1.1 upstream default", UpstreamHttp2Tests.ExistingHttp1UpstreamProtocolRemainsDefault),
    ("Upstream HTTP/2 requires HTTPS", Sync(UpstreamHttp2Tests.Http2UpstreamRequiresHttps)),
    ("Unsupported upstream protocol is rejected", Sync(UpstreamHttp2Tests.UnsupportedUpstreamProtocolIsRejected)),
    ("Upstream pool key differs for HTTP/1.1 and HTTP/2", Sync(UpstreamHttp2Tests.PoolKeyDiffersForHttp1AndHttp2)),
    ("Upstream HTTP/2 advertises h2 ALPN", UpstreamHttp2Tests.UpstreamAlpnAdvertisesHttp2),
    ("Upstream HTTP/2 ALPN failure does not fallback", UpstreamHttp2Tests.AlpnFailureDoesNotFallbackToHttp1),
    ("Upstream HTTP/2 proxy maps headers query and response", UpstreamHttp2Tests.Http2UpstreamProxyMapsHeadersQueryAndResponse),
    ("Upstream HTTP/2 forwards request body", UpstreamHttp2Tests.Http2UpstreamForwardsRequestBody),
    ("Upstream HTTP/2 ends zero-length request body", UpstreamHttp2Tests.Http2UpstreamEndsZeroLengthRequestBody),
    ("Cache works with HTTP/2 upstream", UpstreamHttp2Tests.CacheWorksWithHttp2Upstream),
    ("HTTP/2 upstream health check uses h2 and rejects wrong ALPN", UpstreamHttp2Tests.Http2HealthCheckUsesH2AndRejectsWrongAlpn),
    ("Metrics include upstream HTTP/2 counters", UpstreamHttp2Tests.MetricsIncludeUpstreamHttp2Counters),
    ("Existing HTTP/1.1 and HTTP/2 listener protocols still validate", Sync(Http3InfrastructureTests.ExistingHttp1AndHttp2ProtocolsStillValidate)),
    ("HTTP/3 defaults on for eligible TLS listeners", Sync(Http3InfrastructureTests.Http3DefaultEnabledForEligibleTlsListener)),
    ("HTTP/3 defaults off for plaintext listeners", Sync(Http3InfrastructureTests.Http3DefaultDisabledForPlaintextListener)),
    ("HTTP/3 preview protocol no longer requires experimental gate for default enablement", Sync(Http3InfrastructureTests.Http3PreviewProtocolDoesNotRequireExperimentalGateForDefaultEnablement)),
    ("HTTP/3 preview requires TLS certificate capable listener", Sync(Http3InfrastructureTests.Http3PreviewRequiresTlsCertificateCapableListener)),
    ("HTTP/3 preview config is accepted with gate and enables preview traffic", Sync(Http3InfrastructureTests.Http3PreviewConfigIsAcceptedWithExplicitGateAndEnablesPreviewTraffic)),
    ("HTTP/3-only preview does not enable TCP traffic", Sync(Http3InfrastructureTests.Http3OnlyPreviewDoesNotEnableTcpTraffic)),
    ("TCP listener identity remains unchanged", Sync(Http3InfrastructureTests.TcpListenerIdentityRemainsUnchanged)),
    ("Future QUIC listener identity is separate from TCP identity", Sync(Http3InfrastructureTests.FutureQuicListenerIdentityIsSeparateFromTcpIdentity)),
    ("TCP ALPN does not advertise HTTP/3", Sync(Http3InfrastructureTests.TcpAlpnDoesNotAdvertiseHttp3)),
    ("Status and effective projection report HTTP/3 preview enabled", Sync(Http3InfrastructureTests.StatusAndEffectiveProjectionReportHttp3PreviewEnabled)),
    ("HTTP/3 upstream protocol is still rejected", Sync(Http3InfrastructureTests.UpstreamProtocolStillRejectsHttp3)),
    ("HTTP/3 defaults on for eligible TLS runtime listener", Sync(ClientHttp3PreviewTests.Http3DefaultEnabledForEligibleTlsListener)),
    ("Explicit HTTP/3 disable prevents traffic", Sync(ClientHttp3PreviewTests.ExplicitHttp3DisablePreventsTraffic)),
    ("HTTP/3 preview QUIC listener identity is separate from TCP identity", Sync(ClientHttp3PreviewTests.QuicListenerIdentityIsSeparateFromTcpIdentity)),
    ("Failed HTTP/3 QUIC listener start does not break TCP listener", ClientHttp3PreviewTests.FailedQuicListenerStartDoesNotBreakTcpListener),
    ("Default HTTP/3 TLS listener starts QUIC and emits Alt-Svc", ClientHttp3PreviewTests.DefaultHttp3TlsListenerStartsQuicAndEmitsAltSvc),
    ("Successful reload can add and remove HTTP/3 preview QUIC listener", ClientHttp3PreviewTests.SuccessfulReloadCanAddAndRemovePreviewQuicListener),
    ("Failed reload preserves old HTTP/3 preview listener set", ClientHttp3PreviewTests.FailedReloadPreservesOldPreviewQuicListenerSet),
    ("Status and effective config mark HTTP/3 as experimental preview", Sync(ClientHttp3PreviewTests.StatusAndEffectiveConfigMarkHttp3AsExperimentalPreview)),
    ("HTTP/3 beta enablement is explicitly projected", Sync(ClientHttp3PreviewTests.Http3BetaEnablementIsExplicitlyProjected)),
    ("HTTP/3 Alt-Svc is absent when HTTP/3 is explicitly disabled", ClientHttp3PreviewTests.AltSvcIsAbsentWhenHttp3ExplicitlyDisabled),
    ("HTTP/3 Alt-Svc is emitted only when configured and ready", ClientHttp3PreviewTests.AltSvcIsEmittedOnlyWhenConfiguredAndReady),
    ("HTTP/3 Alt-Svc is not emitted when QUIC listener is not ready", ClientHttp3PreviewTests.AltSvcIsNotEmittedWhenQuicListenerIsNotReady),
    ("Admin responses do not emit HTTP/3 Alt-Svc", Sync(ClientHttp3PreviewTests.AdminResponsesDoNotEmitAltSvc)),
    ("Minimal HTTP/3 GET can reach generated route", ClientHttp3PreviewTests.MinimalHttp3GetCanReachGeneratedRoute),
    ("HTTP/3 HEAD returns headers without body", ClientHttp3PreviewTests.HeadReturnsHeadersWithoutBody),
    ("HTTP/3 generated redirect route works", ClientHttp3PreviewTests.Http3GeneratedRedirectRouteWorks),
    ("HTTP/3 generated maintenance route works", ClientHttp3PreviewTests.Http3GeneratedMaintenanceRouteWorks),
    ("HTTP/3 route miss returns safe 404", ClientHttp3PreviewTests.Http3RouteMissReturnsSafe404),
    ("HTTP/3 GET proxy route works", ClientHttp3PreviewTests.Http3GetProxyRouteWorks),
    ("HTTP/3 HEAD proxy route works", ClientHttp3PreviewTests.Http3HeadProxyRouteWorks),
    ("HTTP/3 proxy preserves query string", ClientHttp3PreviewTests.Http3ProxyPreservesQueryString),
    ("HTTP/3 proxy strips pseudo headers before upstream", ClientHttp3PreviewTests.Http3ProxyStripsPseudoHeadersBeforeUpstream),
    ("HTTP/3 response headers are encoded safely", ClientHttp3PreviewTests.Http3ResponseHeadersAreEncodedSafely),
    ("HTTP/3 chunked response streams body without Transfer-Encoding", ClientHttp3PreviewTests.Http3ChunkedResponseStreamsBodyWithoutTransferEncoding),
    ("HTTP/3 response streams before upstream completes", ClientHttp3PreviewTests.Http3ResponseStreamsBeforeUpstreamCompletes),
    ("HTTP/3 cache interaction uses stored response", ClientHttp3PreviewTests.Http3CacheInteractionUsesStoredResponse),
    ("HTTP/3 oversized cache candidate streams but is not cached", ClientHttp3PreviewTests.Http3OversizedCacheCandidateStreamsButIsNotCached),
    ("HTTP/3 retry for GET can reach second upstream", ClientHttp3PreviewTests.Http3RetryForGetCanReachSecondUpstream),
    ("HTTP/3 unsupported CONNECT is rejected", ClientHttp3PreviewTests.UnsupportedConnectIsRejected),
    ("HTTP/3 POST with bounded body reaches upstream", ClientHttp3PreviewTests.Http3PostWithBoundedBodyReachesUpstream),
    ("HTTP/3 PUT PATCH and DELETE bodies reach upstream", ClientHttp3PreviewTests.Http3PutPatchAndDeleteBodiesReachUpstream),
    ("HTTP/3 path rewrite applies to proxy route", ClientHttp3PreviewTests.Http3PathRewriteAppliesToProxyRoute),
    ("HTTP/3 body size limit applies", ClientHttp3PreviewTests.Http3BodySizeLimitApplies),
    ("HTTP/3 legacy buffered request body limit does not block streaming", ClientHttp3PreviewTests.Http3LegacyBufferedRequestBodyLimitDoesNotBlockStreaming),
    ("HTTP/3 request with body is not retried", ClientHttp3PreviewTests.Http3RequestWithBodyIsNotRetried),
    ("HTTP/3 invalid frame sequence is rejected", ClientHttp3PreviewTests.InvalidFrameSequenceIsRejected),
    ("HTTP/3 unexpected control frame on request stream is rejected", ClientHttp3PreviewTests.UnexpectedControlFrameOnRequestStreamIsRejected),
    ("HTTP/3 protocol error budget closes abusive connection", ClientHttp3PreviewTests.ProtocolErrorBudgetClosesAbusiveConnection),
    ("HTTP/3 malformed pseudo headers are rejected", Sync(ClientHttp3PreviewTests.MalformedPseudoHeadersAreRejected)),
    ("HTTP/3 missing pseudo headers are rejected", Sync(ClientHttp3PreviewTests.MissingPseudoHeadersAreRejected)),
    ("HTTP/3 forbidden connection headers are rejected", Sync(ClientHttp3PreviewTests.ForbiddenConnectionHeadersAreRejected)),
    ("HTTP/3 invalid pseudo header values are rejected", Sync(ClientHttp3PreviewTests.InvalidPseudoHeaderValuesAreRejected)),
    ("HTTP/3 oversized header block is rejected", Sync(ClientHttp3PreviewTests.OversizedHeaderBlockIsRejected)),
    ("HTTP/3 unsupported QPACK dynamic table usage is rejected", Sync(ClientHttp3PreviewTests.UnsupportedQpackDynamicTableUsageIsRejected)),
    ("HTTP/3 unsupported QPACK dynamic table prefix is rejected", Sync(ClientHttp3PreviewTests.UnsupportedQpackDynamicTablePrefixIsRejected)),
    ("Metrics include HTTP/3 preview counters", Sync(ClientHttp3PreviewTests.MetricsIncludeHttp3PreviewCounters)),
    ("Config lint reports HTTP/3 default readiness issues", Sync(ClientHttp3PreviewTests.ConfigLintReportsHttp3DefaultReadinessIssues)),
    ("Resilience disabled preserves existing behavior", ResilienceTests.ExistingBehaviorUnchangedWhenResilienceDisabled),
    ("GET retry occurs on connect failure when enabled", ResilienceTests.GetRetryOccursOnConnectFailureWhenEnabled),
    ("GET retry occurs on configured status when enabled", ResilienceTests.GetRetryOccursOnConfiguredStatusWhenEnabled),
    ("POST is not retried by default", ResilienceTests.PostIsNotRetriedByDefault),
    ("Upgrade requests are not retried", ResilienceTests.UpgradeIsNotRetried),
    ("Request is not retried after response streaming starts", ResilienceTests.RequestIsNotRetriedAfterResponseStreamingStarts),
    ("Retry maxAttempts is enforced", ResilienceTests.RetryMaxAttemptsIsEnforced),
    ("Retry exhausted returns clear failure", ResilienceTests.RetryExhaustedReturnsClearFailure),
    ("Circuit opens after threshold failures", Sync(ResilienceTests.CircuitOpensAfterThresholdFailures)),
    ("Circuit rejects traffic while open", Sync(ResilienceTests.CircuitRejectsTrafficWhileOpen)),
    ("Circuit transitions to half-open after open duration", Sync(ResilienceTests.CircuitTransitionsToHalfOpenAfterOpenDuration)),
    ("Half-open success closes circuit", Sync(ResilienceTests.HalfOpenSuccessClosesCircuit)),
    ("Half-open failure reopens circuit", Sync(ResilienceTests.HalfOpenFailureReopensCircuit)),
    ("Weighted round-robin honors weights", Sync(ResilienceTests.WeightedRoundRobinHonorsWeights)),
    ("Equal weights preserve round-robin order", Sync(ResilienceTests.EqualWeightRoundRobinPreservesExistingOrder)),
    ("Unhealthy and open-circuit upstreams are skipped", Sync(ResilienceTests.UnhealthyAndOpenCircuitUpstreamsAreSkipped)),
    ("All unavailable upstreams return no selection", Sync(ResilienceTests.AllUpstreamsUnavailableReturnsNoSelection)),
    ("All unavailable upstreams return safe failure", ResilienceTests.AllUnavailableUpstreamsReturnSafeFailure),
    ("Metrics include retry circuit and balancing counters", Sync(ResilienceTests.MetricsIncludeRetryCircuitAndBalancingCounters)),
    ("Effective and status projections show resilience state", Sync(ResilienceTests.EffectiveAndStatusProjectionsShowSafeResilienceState)),
    ("Host startup succeeds from fresh data directory", StartupSmokeTests.StartsFromFreshDataDirectory),
    ("Host startup fails when existing site config is invalid", StartupSmokeTests.FailsStartupWhenExistingSiteConfigIsInvalid),
    ("Host startup succeeds with valid site config", StartupSmokeTests.StartsWithValidSiteConfig),
    ("Proxy dataplane proxies one GET request end to end", ProxyIntegrationTests.ProxiesSingleGetToUpstream),
    ("Proxy dataplane proxies fixed-length request and response", ProxyIntegrationTests.ProxiesFixedLengthRequestAndResponse),
    ("Proxy dataplane proxies chunked request and response", ProxyIntegrationTests.ProxiesChunkedRequestAndResponse),
    ("Proxy dataplane does not relay HEAD response body", ProxyIntegrationTests.DoesNotRelayHeadResponseBody),
    ("Proxy dataplane proxies 204 without response body", ProxyIntegrationTests.ProxiesNoContentWithoutBody),
    ("Proxy dataplane proxies 304 without response body", ProxyIntegrationTests.ProxiesNotModifiedWithoutBody),
    ("Proxy dataplane rejects invalid request framing", ProxyIntegrationTests.RejectsInvalidRequestFraming),
    ("Proxy dataplane rejects malformed chunked request body", ProxyIntegrationTests.RejectsMalformedChunkedRequestBody),
    ("Proxy dataplane filters hop-by-hop request headers", ProxyIntegrationTests.FiltersHopByHopRequestHeaders),
    ("Proxy dataplane preserves Host header", ProxyIntegrationTests.PreservesHostHeader),
    ("Proxy dataplane emits generated response request ID", ProxyIntegrationTests.ResponseIncludesGeneratedRequestId),
    ("Proxy dataplane preserves external request ID in diagnostics", ProxyIntegrationTests.ExternalRequestIdIsPreservedInDiagnostics),
    ("Proxy dataplane records successful diagnostics", ProxyIntegrationTests.SuccessfulRequestProducesDiagnosticRouteAndUpstream),
    ("Proxy dataplane records upstream connect failure diagnostics", ProxyIntegrationTests.UpstreamConnectFailureProducesDiagnosticClassification),
    ("Proxy dataplane can disable access logs while keeping diagnostics", ProxyIntegrationTests.AccessLoggingCanBeDisabledWhileDiagnosticsRemainEnabled),
    ("HTTP to HTTPS redirect preserves path and query", ProxyIntegrationTests.HttpToHttpsRedirectPreservesPathAndQuery),
    ("Canonical host redirect works", ProxyIntegrationTests.CanonicalHostRedirectWorks),
    ("Canonical host redirect does not loop", ProxyIntegrationTests.CanonicalHostRedirectDoesNotLoop),
    ("Forwarded headers generated for untrusted direct client", ProxyIntegrationTests.ForwardedHeadersGeneratedForUntrustedDirectClient),
    ("Trusted proxy accepts prior forwarded chain", ProxyIntegrationTests.TrustedProxyAcceptsPriorForwardedChain),
    ("Untrusted client forwarded headers are stripped and replaced", ProxyIntegrationTests.UntrustedClientForwardedHeadersAreStrippedAndReplaced),
    ("Request header set/remove rules apply upstream", ProxyIntegrationTests.RequestHeaderSetAndRemoveRulesApplyUpstream),
    ("Response header set/remove rules apply downstream", ProxyIntegrationTests.ResponseHeaderSetAndRemoveRulesApplyDownstream),
    ("Path prefix stripping preserves query string", ProxyIntegrationTests.PathPrefixStrippingPreservesQueryString),
    ("Path prefix replacement works", ProxyIntegrationTests.PathPrefixReplacementWorks),
    ("Path rewrite no-match forwards original target", ProxyIntegrationTests.PathRewriteNoMatchForwardsOriginalTarget),
    ("Redirect route returns configured redirect", ProxyIntegrationTests.RedirectRouteReturnsConfiguredRedirect),
    ("Static response route returns configured response", ProxyIntegrationTests.StaticResponseRouteReturnsConfiguredResponse),
    ("Maintenance mode returns 503 and does not contact upstream", ProxyIntegrationTests.MaintenanceModeReturns503AndDoesNotContactUpstream),
    ("Per-route body-size override works", ProxyIntegrationTests.PerRouteBodySizeOverrideWorks),
    ("Per-route access-log disable is reflected in diagnostics", ProxyIntegrationTests.PerRouteAccessLogDisableIsReflectedInDiagnostics),
    ("Proxy dataplane records no-route diagnostics and status summary", ProxyIntegrationTests.NoMatchingRouteProducesDiagnosticClassification),
    ("Proxy dataplane rejects oversized request head", ProxyIntegrationTests.OversizedRequestHeadIsRejected),
    ("Proxy dataplane rejects excessive header count", ProxyIntegrationTests.ExcessiveHeaderCountIsRejected),
    ("Proxy dataplane rejects excessive header line", ProxyIntegrationTests.ExcessiveHeaderLineIsRejected),
    ("Proxy dataplane rejects excessive request body size", ProxyIntegrationTests.ExcessiveRequestBodySizeIsRejected),
    ("Proxy dataplane rejects oversized chunked request body", ProxyIntegrationTests.ChunkedRequestBodySizeIsRejected),
    ("Proxy dataplane enforces per-IP request rate limit", ProxyIntegrationTests.PerIpRequestRateLimitIsEnforced),
    ("Proxy dataplane times out incomplete request head", ProxyIntegrationTests.TimesOutIncompleteRequestHead),
    ("Proxy dataplane times out incomplete Content-Length request body", ProxyIntegrationTests.TimesOutIncompleteContentLengthRequestBody),
    ("Proxy dataplane times out incomplete chunked request body", ProxyIntegrationTests.TimesOutIncompleteChunkedRequestBody),
    ("Proxy dataplane maps unavailable upstream to 502", ProxyIntegrationTests.UnavailableUpstreamProducesBadGateway),
    ("Proxy dataplane maps upstream response-head timeout to 504", ProxyIntegrationTests.UpstreamResponseHeadTimeoutProducesGatewayTimeout),
    ("Proxy dataplane closes after started response on upstream early close", ProxyIntegrationTests.UpstreamContentLengthEarlyCloseClosesAfterStartedResponse),
    ("HTTPS listener proxies GET to upstream", ProxyIntegrationTests.HttpsListenerProxiesGetToUpstream),
    ("HTTPS listener selects certificate by SNI", ProxyIntegrationTests.HttpsListenerSelectsCertificateBySni),
    ("HTTPS listener uses default certificate for unmatched SNI", ProxyIntegrationTests.HttpsListenerUsesDefaultCertificateForUnmatchedSni),
    ("HTTPS listener uses default certificate without SNI", ProxyIntegrationTests.HttpsListenerUsesDefaultCertificateWithoutSni),
    ("HTTPS listener fails handshake when no certificate matches", ProxyIntegrationTests.HttpsListenerFailsHandshakeWhenNoCertificateMatches),
    ("HTTPS listener times out incomplete TLS handshake", ProxyIntegrationTests.HttpsListenerTimesOutIncompleteTlsHandshake),
    ("Persistent client processes two sequential GETs and reuses upstream", ProxyIntegrationTests.PersistentClientProcessesTwoSequentialGetsAndReusesUpstream),
    ("Client Connection close header closes after response", ProxyIntegrationTests.ClientConnectionCloseHeaderClosesAfterResponse),
    ("HTTP/1.0 client closes by default", ProxyIntegrationTests.Http10ClientClosesByDefault),
    ("Max requests per client connection is enforced", ProxyIntegrationTests.MaxRequestsPerClientConnectionIsEnforced),
    ("Client keep-alive idle timeout closes connection", ProxyIntegrationTests.ClientKeepAliveIdleTimeoutClosesConnection),
    ("Malformed second request closes connection", ProxyIntegrationTests.MalformedSecondRequestClosesConnection),
    ("Persistent client proxies Content-Length POST", ProxyIntegrationTests.PersistentClientProxiesContentLengthPost),
    ("Persistent client proxies chunked POST", ProxyIntegrationTests.PersistentClientProxiesChunkedPost),
    ("Upstream connection is not reused after response Connection close", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterResponseConnectionClose),
    ("Upstream connection is not reused after premature disconnect", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterPrematureDisconnect),
    ("Upstream connection is not reused after framing error", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterFramingError),
    ("WebSocket Upgrade over plaintext returns 101", ProxyIntegrationTests.WebSocketUpgradeOverPlaintextReturnsSwitchingProtocols),
    ("WebSocket Upgrade produces tunnel diagnostic", ProxyIntegrationTests.WebSocketUpgradeProducesTunnelDiagnostic),
    ("WebSocket tunnel relays client bytes upstream", ProxyIntegrationTests.WebSocketTunnelRelaysClientBytesToUpstream),
    ("WebSocket tunnel relays upstream bytes client", ProxyIntegrationTests.WebSocketTunnelRelaysUpstreamBytesToClient),
    ("WebSocket tunnel closes when client closes", ProxyIntegrationTests.WebSocketTunnelClosesWhenClientCloses),
    ("WebSocket tunnel closes when upstream closes", ProxyIntegrationTests.WebSocketTunnelClosesWhenUpstreamCloses),
    ("WebSocket tunnel idle timeout closes tunnel", ProxyIntegrationTests.WebSocketTunnelIdleTimeoutClosesTunnel),
    ("WebSocket Upgrade over HTTPS returns 101", ProxyIntegrationTests.WebSocketUpgradeOverHttpsReturnsSwitchingProtocols),
    ("Upgrade does not use normal upstream pool", ProxyIntegrationTests.UpgradeDoesNotUseNormalUpstreamPool),
    ("Missing WebSocket headers are rejected", ProxyIntegrationTests.MissingWebSocketHeadersAreRejected),
    ("Upstream non-101 Upgrade response is forwarded and closed", ProxyIntegrationTests.UpstreamNon101UpgradeResponseIsForwardedAndClosed),
    ("Malformed 101 Upgrade response produces bad gateway", ProxyIntegrationTests.MalformedSwitchingProtocolsResponseProducesBadGateway),
    ("Health check 2xx response is healthy", HealthCheckTests.HealthCheck2xxIsHealthy),
    ("Health check 3xx response is healthy", HealthCheckTests.HealthCheck3xxIsHealthy),
    ("Health check 4xx response is unhealthy", HealthCheckTests.HealthCheck4xxIsUnhealthy),
    ("Health check 5xx response is unhealthy", HealthCheckTests.HealthCheck5xxIsUnhealthy),
    ("Health check timeout is unhealthy", HealthCheckTests.HealthCheckTimeoutIsUnhealthy),
    ("Health state transitions to unhealthy after threshold", Sync(HealthCheckTests.HealthStateTransitionsToUnhealthyAfterThreshold)),
    ("Health state transitions to healthy after recovery threshold", Sync(HealthCheckTests.HealthStateTransitionsToHealthyAfterRecoveryThreshold)),
    ("Round-robin distributes sequential requests across two upstreams", ProxyIntegrationTests.RoundRobinDistributesSequentialRequestsAcrossTwoUpstreams),
    ("Unhealthy upstream is not selected", ProxyIntegrationTests.UnhealthyUpstreamIsNotSelected),
    ("All unhealthy upstreams return service unavailable", ProxyIntegrationTests.AllUnhealthyUpstreamsReturnServiceUnavailable),
    ("WebSocket Upgrade uses round-robin upstream selection", ProxyIntegrationTests.WebSocketUpgradeUsesRoundRobinUpstreamSelection),
    ("Upstream pool uses distinct endpoint keys", ProxyIntegrationTests.UpstreamPoolUsesDistinctEndpointKeys),
    ("Recent diagnostics store is bounded", Sync(ObservabilityTests.RecentDiagnosticsStoreIsBounded)),
    ("Diagnostics controller honors safe limit", Sync(ObservabilityTests.DiagnosticsControllerHonorsSafeLimit)),
    ("Diagnostics event omits bodies and secrets", Sync(ObservabilityTests.DiagnosticsEventDoesNotCarryBodiesOrSecrets)),
    ("Admission controller enforces client limit", Sync(HardeningTests.AdmissionControllerEnforcesClientLimit)),
    ("Admission controller enforces TLS handshake limit", Sync(HardeningTests.AdmissionControllerEnforcesTlsHandshakeLimit)),
    ("Rate limiter enforces request limit and refill", Sync(HardeningTests.RateLimiterEnforcesRequestLimitAndRefills)),
    ("Rate limiter enforces upgrade limit", Sync(HardeningTests.RateLimiterEnforcesUpgradeLimit)),
    ("Rate limiter cleans stale entries", Sync(HardeningTests.RateLimiterCleansStaleEntries)),
    ("Shutdown coordinator exposes grace deadline", Sync(HardeningTests.ShutdownCoordinatorExposesGraceDeadlineAndCancels))
};

var failures = 0;

foreach (var test in tests)
{
    try
    {
        await test.Run();
        Console.WriteLine($"PASS {test.Name}");
    }
    catch (Exception exception)
    {
        failures++;
        Console.Error.WriteLine($"FAIL {test.Name}");
        Console.Error.WriteLine(exception);
    }
}

if (failures > 0)
{
    Environment.ExitCode = 1;
    return;
}

Console.WriteLine($"Passed {tests.Length} tests.");

static Func<Task> Sync(Action test)
{
    return () =>
    {
        test();
        return Task.CompletedTask;
    };
}
