namespace MDRAVA.Tests;

internal static partial class TestRegistry
{
    private static TestCase[] FoundationAndConfig() =>
    [
    Test("Project references preserve layered dependency direction", Sync(ArchitectureBoundaryTests.ProjectReferencesPreserveLayeredDependencyDirection), TestTaxonomy.Config),
    Test("Configuration file error names global and path errors", Sync(ConfigurationTests.ConfigurationFileErrorNamesGlobalAndPathErrors), TestTaxonomy.Config),
    Test("Normalize site parse result names parsed and failed states", Sync(ConfigurationTests.NormalizeSiteParseResultNamesParsedAndFailedStates), TestTaxonomy.Config),
    Test("Configuration normalize result names normalized and failed outcomes", Sync(ConfigurationTests.ConfigurationNormalizeResultNamesNormalizedAndFailedOutcomes), TestTaxonomy.Config),
    Test("Configuration reload result names reload outcomes", Sync(ConfigurationTests.ConfigurationReloadResultNamesReloadOutcomes), TestTaxonomy.Config),
    Test("Configuration validation result names validation outcomes", Sync(ConfigurationTests.ConfigurationValidationResultNamesValidationOutcomes), TestTaxonomy.Config),
    Test("Configuration read result names available and missing outcomes", Sync(ConfigurationTests.ConfigurationReadResultNamesAvailableAndMissingOutcomes), TestTaxonomy.Config),
    Test("Configuration load result names loaded validated and failed outcomes", ConfigurationTests.ConfigurationLoadResultNamesLoadedValidatedAndFailedOutcomes, TestTaxonomy.Config),
    Test("Http1RequestParser parses a valid GET request", Sync(Http1RequestParserTests.ParsesValidGet), TestTaxonomy.Http1),
    Test("Http1RequestParser rejects missing Host", Sync(Http1RequestParserTests.RejectsMissingHost), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1RequestParser rejects invalid Content-Length", Sync(Http1RequestParserTests.RejectsInvalidContentLength), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1RequestParser detects request bodies", Sync(Http1RequestParserTests.DetectsRequestBodyIndicators), TestTaxonomy.Http1),
    Test("Http1RequestParser parses chunked transfer encoding", Sync(Http1RequestParserTests.ParsesChunkedTransferEncoding), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Http1RequestParser rejects conflicting Content-Length", Sync(Http1RequestParserTests.RejectsConflictingContentLength), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1RequestParser rejects Content-Length with Transfer-Encoding", Sync(Http1RequestParserTests.RejectsContentLengthWithTransferEncoding), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1RequestParser rejects unsupported Transfer-Encoding", Sync(Http1RequestParserTests.RejectsUnsupportedTransferEncoding), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1ChunkSizeParser parses chunk size line", Sync(Http1ChunkSizeParserTests.ParsesChunkSizeLine), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Http1ChunkSizeParser parses chunk extension", Sync(Http1ChunkSizeParserTests.ParsesChunkSizeWithExtension), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Http1ChunkSizeParser rejects invalid line", Sync(Http1ChunkSizeParserTests.RejectsInvalidChunkSizeLine), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1ChunkSizeParser rejects missing CRLF", Sync(Http1ChunkSizeParserTests.RejectsMissingCrlf), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1ChunkSizeParser rejects overflow", Sync(Http1ChunkSizeParserTests.RejectsOverflow), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http1ResponseParser parses Content-Length response", Sync(Http1ResponseParserTests.ParsesContentLengthResponse), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Http1ResponseParser treats zero Content-Length as no body", Sync(Http1ResponseParserTests.TreatsZeroContentLengthAsNoBody), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Http1ResponseParser parses chunked response", Sync(Http1ResponseParserTests.ParsesChunkedResponse), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Http1ResponseParser treats HEAD response as no body", Sync(Http1ResponseParserTests.TreatsHeadResponseAsNoBody), TestTaxonomy.Http1),
    Test("Http1ResponseParser treats 204 as no body", Sync(Http1ResponseParserTests.TreatsNoContentAsNoBody), TestTaxonomy.Http1),
    Test("Http1ResponseParser treats 304 as no body", Sync(Http1ResponseParserTests.TreatsNotModifiedAsNoBody), TestTaxonomy.Http1),
    Test("Http1ResponseParser rejects invalid Content-Length", Sync(Http1ResponseParserTests.RejectsInvalidResponseContentLength), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Framed upstream response policy builds HTTP/1 heads from narrow facts", Sync(FramedUpstreamResponsePolicyTests.BuildsHttp1HeadFromNarrowUpstreamFacts), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("Http2 header policy classifies allowed request pseudo headers", Sync(Http2HeaderPolicyTests.ClassifiesAllowedRequestPseudoHeaders), TestTaxonomy.Http2, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http2 header policy classifies forbidden request headers", Sync(Http2HeaderPolicyTests.ClassifiesForbiddenRequestHeaders), TestTaxonomy.Http2, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Http2 header policy classifies managed upstream request headers", Sync(Http2HeaderPolicyTests.ClassifiesManagedUpstreamRequestHeaders), TestTaxonomy.Http2, TestTaxonomy.Headers),
    Test("Http1 client connection policy keeps HTTP/1.1 open by default", Sync(Http1ClientConnectionPolicyTests.KeepsHttp11OpenByDefault), TestTaxonomy.Http1),
    Test("Http1 client connection policy closes on Connection close", Sync(Http1ClientConnectionPolicyTests.ClosesWhenConnectionCloseIsPresent), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Http1 client connection policy closes HTTP/1.0 by default", Sync(Http1ClientConnectionPolicyTests.ClosesHttp10ByDefault), TestTaxonomy.Http1),
    Test("Generated failure policy allows responses only before downstream start and without suppression", Sync(ProxyGeneratedFailurePolicyTests.AllowsGeneratedFailureOnlyBeforeResponseAndWithoutSuppression), TestTaxonomy.Http1, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Http1 request framing policy classifies framed request bodies", Sync(Http1RequestFramingPolicyTests.ClassifiesFramedRequestBodies), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.Http3),
    Test("Timeout failure policy classifies forwarding failures", Sync(ProxyTimeoutFailurePolicyTests.ClassifiesForwardingTimeoutFailures), TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Request method policy validates HTTP method tokens", Sync(ProxyRequestMethodPolicyTests.ValidatesHttpMethodTokens), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("Request method policy classifies supported methods", Sync(ProxyRequestMethodPolicyTests.ClassifiesSupportedApplicationMethods), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.Http3),
    Test("Request method policy classifies safe read methods", Sync(ProxyRequestMethodPolicyTests.ClassifiesSafeReadMethods), TestTaxonomy.Http1, TestTaxonomy.Caching, TestTaxonomy.RetryCircuit),
    Test("Request method policy classifies unsupported methods", Sync(ProxyRequestMethodPolicyTests.ClassifiesUnsupportedMethods), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("Upgrade request policy validates accepted WebSocket upgrades", Sync(UpgradeRequestPolicyTests.ValidatesAcceptedWebSocketUpgrade), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Upgrade request policy rejects request bodies", Sync(UpgradeRequestPolicyTests.RejectsUpgradeRequestBodies), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Upgrade request policy classifies managed upgrade headers", Sync(UpgradeRequestPolicyTests.ClassifiesManagedUpgradeHeaders), TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Upgrade request policy classifies unsafe switching protocols response headers", Sync(UpgradeRequestPolicyTests.ClassifiesUnsafeSwitchingProtocolsResponseHeaders), TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Header policy filters standard hop-by-hop headers", Sync(HeaderPolicyTests.FiltersStandardHopByHopHeaders), TestTaxonomy.Headers),
    Test("Header policy filters Connection-nominated headers", Sync(HeaderPolicyTests.FiltersConnectionNominatedHeaders), TestTaxonomy.Headers),
    Test("Header policy classifies hop-by-hop names and Connection tokens", Sync(HeaderPolicyTests.ClassifiesHopByHopNamesAndConnectionTokens), TestTaxonomy.Headers),
    Test("Header policy classifies managed HTTP/1 framing headers", Sync(HeaderPolicyTests.ClassifiesManagedHttp1FramingHeaders), TestTaxonomy.Headers),
    Test("Header policy classifies managed stored response headers", Sync(HeaderPolicyTests.ClassifiesManagedStoredResponseHeaders), TestTaxonomy.Headers, TestTaxonomy.Caching),
    Test("Header mutation policy applies request changes", Sync(HeaderPolicyTests.AppliesRequestHeaderMutationPolicy), TestTaxonomy.Headers),
    Test("Forwarded address policy names normalized address", Sync(HeaderPolicyTests.ForwardedAddressPolicyNamesNormalizedAddress), TestTaxonomy.Headers),
    Test("Forwarded address policy names missing address", Sync(HeaderPolicyTests.ForwardedAddressPolicyNamesMissingAddress), TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Header mutation policy applies response changes", Sync(HeaderPolicyTests.AppliesResponseHeaderMutationPolicy), TestTaxonomy.Headers),
    Test("SingleUpstreamRouteMatcher matches wildcard route", Sync(RouteMatcherTests.MatchesWildcardRoute), TestTaxonomy.Routing),
    Test("SingleUpstreamRouteMatcher matches host without request port", Sync(RouteMatcherTests.MatchesHostWithoutRequestPort), TestTaxonomy.Routing, TestTaxonomy.Headers),
    Test("SingleUpstreamRouteMatcher exact host route beats wildcard fallback", Sync(RouteMatcherTests.ExactHostRouteBeatsWildcardFallbackWhenBothCouldMatch), TestTaxonomy.Routing, TestTaxonomy.Headers),
    Test("SingleUpstreamRouteMatcher port-specific host route beats host fallback", Sync(RouteMatcherTests.PortSpecificHostRouteBeatsHostFallbackWhenAuthorityIncludesPort), TestTaxonomy.Routing, TestTaxonomy.Headers),
    Test("SingleUpstreamRouteMatcher specific route path beats catch-all fallback", Sync(RouteMatcherTests.SpecificRoutePathBeatsCatchAllFallbackWhenBothCouldMatch), TestTaxonomy.Routing),
    Test("SingleUpstreamRouteMatcher reads runtime routes without configuration snapshot", Sync(RouteMatcherTests.MatchesRuntimeRoutesWithoutConfigurationSnapshot), TestTaxonomy.Routing, TestTaxonomy.Config),
    Test("Data directory uses configured override", Sync(ConfigurationTests.DataDirectoryUsesConfiguredOverride), TestTaxonomy.Config),
    Test("Data directory uses environment override", Sync(ConfigurationTests.DataDirectoryUsesEnvironmentOverride), TestTaxonomy.Config),
    Test("Data directory defaults under local application data when available", Sync(ConfigurationTests.DataDirectoryDefaultsUnderLocalApplicationDataWhenAvailable), TestTaxonomy.Config),
    Test("Loader loads valid per-site JSON config files", ConfigurationTests.LoaderLoadsValidSiteFiles, TestTaxonomy.Config),
    Test("Loader loads equivalent JSON and YAML site files", ConfigurationTests.LoaderLoadsEquivalentJsonAndYamlSiteFiles, TestTaxonomy.Config),
    Test("Loader reports YAML parse errors with per-file diagnostics", ConfigurationTests.LoaderReportsYamlParseErrorsWithPerFileDiagnostics, TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Loader loads route load-balancing and health-check settings", ConfigurationTests.LoaderLoadsRouteLoadBalancingAndHealthCheckSettings, TestTaxonomy.Config, TestTaxonomy.Routing),
    Test("Loader creates missing config directories and loads empty snapshot", ConfigurationTests.LoaderCreatesMissingConfigDirectoriesAndLoadsEmptySnapshot, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Loader does not overwrite existing placeholder files", ConfigurationTests.LoaderDoesNotOverwriteExistingPlaceholderFiles, TestTaxonomy.Config),
    Test("Loader loads existing empty sites directory", ConfigurationTests.LoaderLoadsExistingEmptySitesDirectory, TestTaxonomy.Config),
    Test("Loader uses defaults when operational config is missing", ConfigurationTests.LoaderUsesDefaultsWhenOperationalConfigIsMissing, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Loader loads explicit operational timeout settings", ConfigurationTests.LoaderLoadsExplicitOperationalTimeouts, TestTaxonomy.Config, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Loader loads observability defaults", ConfigurationTests.LoaderLoadsObservabilityDefaults, TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Loader loads explicit observability settings", ConfigurationTests.LoaderLoadsExplicitObservabilitySettings, TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Loader rejects invalid observability capacity", ConfigurationTests.LoaderRejectsInvalidObservabilityCapacity, TestTaxonomy.Config, TestTaxonomy.Limits, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Loader rejects invalid log persistence settings", ConfigurationTests.LoaderRejectsInvalidLogPersistenceSettings, TestTaxonomy.Config, TestTaxonomy.Limits, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Loader loads hardening limit defaults", ConfigurationTests.LoaderLoadsLimitDefaults, TestTaxonomy.Config, TestTaxonomy.Limits),
    Test("Loader rejects invalid hardening limits", ConfigurationTests.LoaderRejectsInvalidLimitSettings, TestTaxonomy.Config, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Loader rejects invalid operational timeout settings", ConfigurationTests.LoaderRejectsInvalidOperationalTimeouts, TestTaxonomy.Config, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Loader rejects invalid tunnel connection limit", ConfigurationTests.LoaderRejectsInvalidTunnelLimit, TestTaxonomy.Config, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Loader loads HTTPS listener with certificate", ConfigurationTests.LoaderLoadsHttpsListenerWithCertificate, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Loader rejects HTTPS listener with missing certificate reference", ConfigurationTests.LoaderRejectsHttpsListenerWithMissingCertificateReference, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Loader rejects invalid certificate path", ConfigurationTests.LoaderRejectsInvalidCertificatePath, TestTaxonomy.Config, TestTaxonomy.Routing, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Loader rejects invalid certificate password", ConfigurationTests.LoaderRejectsInvalidCertificatePassword, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Loader rejects duplicate SNI certificate mapping", ConfigurationTests.LoaderRejectsDuplicateSniCertificateMapping, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Loader merges SNI mappings from shared HTTPS listener", ConfigurationTests.LoaderMergesSniMappingsFromSharedHttpsListener, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Loader rejects invalid per-site JSON config files", ConfigurationTests.LoaderRejectsInvalidSiteFile, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Reload preserves active snapshot when load fails", ConfigurationTests.ReloadPreservesActiveSnapshotWhenLoadFails, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Reload replaces active snapshot when load succeeds", ConfigurationTests.ReloadReplacesActiveSnapshotWhenLoadSucceeds, TestTaxonomy.Config),
    Test("Reload replaces active snapshot with empty sites directory", ConfigurationTests.ReloadReplacesActiveSnapshotWithEmptySitesDirectory, TestTaxonomy.Config),
    Test("Active inspection projection reflects store", ConfigurationTests.ActiveInspectionProjectionReflectsStore, TestTaxonomy.Config),
    Test("Config read operations project active and effective from current source", Sync(ConfigurationTests.ConfigReadOperationsProjectActiveAndEffectiveFromCurrentSource), TestTaxonomy.Config),
    Test("Loader rejects unsafe header policy rule", ConfigurationTests.LoaderRejectsUnsafeHeaderRule, TestTaxonomy.Config, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Config response header policy cannot emit hop-by-hop headers", ConfigurationTests.ResponseHeaderPolicyCannotEmitHopByHopHeaders, TestTaxonomy.Config, TestTaxonomy.Headers),
    Test("Config multi-file conflict reporting is deterministic", ConfigurationTests.MultiFileConfigConflictReportingIsDeterministic, TestTaxonomy.Config),
    Test("Config validate reports valid config without applying", ConfigurationTests.ConfigValidateReportsValidWithoutApplying, TestTaxonomy.Config),
    Test("Config validate reports invalid config without replacing active config", ConfigurationTests.ConfigValidateReportsInvalidWithoutReplacingActiveConfig, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Config normalize converts YAML to JSON without applying", ConfigurationTests.ConfigNormalizeConvertsYamlToJsonWithoutApplying, TestTaxonomy.Config),
    Test("Config normalizer shapes validation failures from parsed site", Sync(ConfigurationTests.ConfigNormalizerShapesValidationFailuresFromParsedSite), TestTaxonomy.Config),
    Test("Config normalizer rejects missing canonical JSON", Sync(ConfigurationTests.ConfigNormalizerRejectsMissingCanonicalJson), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Config normalizer rejects missing request body", Sync(ConfigurationTests.ConfigNormalizerRejectsMissingRequestBody), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Config normalizer rejects incomplete request fields", Sync(ConfigurationTests.ConfigNormalizerRejectsIncompleteRequestFields), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Config normalize controller rejects missing request body", Sync(ConfigurationTests.ConfigNormalizeControllerRejectsMissingRequestBody), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Effective config projection redacts certificate secrets", ConfigurationTests.EffectiveConfigProjectionRedactsCertificateSecrets, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Expired certificate projection keeps validity window visible", ConfigurationTests.ExpiredCertificateProjectionKeepsValidityWindowVisible, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Not-yet-valid certificate projection keeps validity window visible", ConfigurationTests.NotYetValidCertificateProjectionKeepsValidityWindowVisible, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Reload failure reports per-file error and preserves active config", ConfigurationTests.ReloadFailureReportsPerFileErrorAndPreservesActiveConfig, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Reload with invalid log persistence config preserves active snapshot", ConfigurationTests.ReloadWithInvalidLogPersistenceConfigPreservesActiveSnapshot, TestTaxonomy.Config, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    ];
}
