namespace MDRAVA.Tests;

internal static partial class TestRegistry
{
    private static TestCase[] ResilienceAndHttp1Proxy() =>
    [
    Test("Resilience disabled preserves existing behavior", ResilienceTests.ExistingBehaviorUnchangedWhenResilienceDisabled, TestTaxonomy.RetryCircuit),
    Test("GET retry occurs on connect failure when enabled", ResilienceTests.GetRetryOccursOnConnectFailureWhenEnabled, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("GET retry occurs on configured status when enabled", ResilienceTests.GetRetryOccursOnConfiguredStatusWhenEnabled, TestTaxonomy.RetryCircuit),
    Test("POST is not retried by default", ResilienceTests.PostIsNotRetriedByDefault, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Upgrade requests are not retried", ResilienceTests.UpgradeIsNotRetried, TestTaxonomy.Http1, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Request is not retried after response streaming starts", ResilienceTests.RequestIsNotRetriedAfterResponseStreamingStarts, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Partial response failure does not retry second upstream after downstream bytes are sent", ResilienceTests.PartialResponseFailureDoesNotRetrySecondUpstreamAfterDownstreamBytesAreSent, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Retry status does not bypass unsafe POST method", ResilienceTests.RetryStatusDoesNotBypassUnsafePostMethod, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Retry maxAttempts is enforced", ResilienceTests.RetryMaxAttemptsIsEnforced, TestTaxonomy.RetryCircuit),
    Test("Retry exhausted returns clear failure", ResilienceTests.RetryExhaustedReturnsClearFailure, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Circuit opens after threshold failures", Sync(ResilienceTests.CircuitOpensAfterThresholdFailures), TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Circuit rejects traffic while open", Sync(ResilienceTests.CircuitRejectsTrafficWhileOpen), TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Circuit transitions to half-open after open duration", Sync(ResilienceTests.CircuitTransitionsToHalfOpenAfterOpenDuration), TestTaxonomy.RetryCircuit),
    Test("Circuit half-open probe count is bounded", Sync(ResilienceTests.HalfOpenProbeCountIsBounded), TestTaxonomy.RetryCircuit, TestTaxonomy.Limits),
    Test("Half-open success closes circuit", Sync(ResilienceTests.HalfOpenSuccessClosesCircuit), TestTaxonomy.RetryCircuit),
    Test("Half-open failure reopens circuit", Sync(ResilienceTests.HalfOpenFailureReopensCircuit), TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Weighted round-robin honors weights", Sync(ResilienceTests.WeightedRoundRobinHonorsWeights), TestTaxonomy.RetryCircuit),
    Test("Equal weights preserve round-robin order", Sync(ResilienceTests.EqualWeightRoundRobinPreservesExistingOrder), TestTaxonomy.RetryCircuit),
    Test("Unhealthy and open-circuit upstreams are skipped", Sync(ResilienceTests.UnhealthyAndOpenCircuitUpstreamsAreSkipped), TestTaxonomy.RetryCircuit, TestTaxonomy.HealthChecks, TestTaxonomy.SecurityNegativePaths),
    Test("Mixed protocol upstream failures isolate circuit state", Sync(ResilienceTests.MixedProtocolUpstreamFailuresIsolateCircuitState), TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("All unavailable upstreams return no selection", Sync(ResilienceTests.AllUpstreamsUnavailableReturnsNoSelection), TestTaxonomy.Routing, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("All unavailable upstreams return safe failure", ResilienceTests.AllUnavailableUpstreamsReturnSafeFailure, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Metrics include retry circuit and balancing counters", Sync(ResilienceTests.MetricsIncludeRetryCircuitAndBalancingCounters), TestTaxonomy.RetryCircuit, TestTaxonomy.Metrics),
    Test("Effective and status projections show resilience state", Sync(ResilienceTests.EffectiveAndStatusProjectionsShowSafeResilienceState), TestTaxonomy.Config, TestTaxonomy.RetryCircuit),
    Test("Retry policy suppresses configured status only when allowed", Sync(ResilienceTests.RetryPolicySuppressesConfiguredStatusOnlyWhenAllowed), TestTaxonomy.RetryCircuit),
    Test("Timeout policy applies route and retry attempt timeouts", Sync(ResilienceTests.TimeoutPolicyAppliesRouteAndRetryAttemptTimeouts), TestTaxonomy.RetryCircuit, TestTaxonomy.Limits),
    Test("Host startup succeeds from fresh data directory", StartupSmokeTests.StartsFromFreshDataDirectory, TestTaxonomy.Config, TestTaxonomy.Headers),
    Test("Host startup fails when existing site config is invalid", StartupSmokeTests.FailsStartupWhenExistingSiteConfigIsInvalid, TestTaxonomy.Config, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Host startup succeeds with valid site config", StartupSmokeTests.StartsWithValidSiteConfig, TestTaxonomy.Config, TestTaxonomy.Headers),
    Test("Proxy dataplane proxies one GET request end to end", ProxyIntegrationTests.ProxiesSingleGetToUpstream, TestTaxonomy.Http1),
    Test("Proxy dataplane proxies fixed-length request and response", ProxyIntegrationTests.ProxiesFixedLengthRequestAndResponse, TestTaxonomy.Http1),
    Test("Proxy dataplane proxies chunked request and response", ProxyIntegrationTests.ProxiesChunkedRequestAndResponse, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("HTTP/1.1 chunk extensions are accepted and forwarded", ProxyIntegrationTests.AcceptsChunkExtensionsAndForwardsChunkedBody, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("HTTP/1.1 declared chunked request trailer is forwarded", ProxyIntegrationTests.ForwardsDeclaredChunkedRequestTrailer, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Proxy dataplane does not relay HEAD response body", ProxyIntegrationTests.DoesNotRelayHeadResponseBody, TestTaxonomy.Http1),
    Test("Proxy dataplane proxies 204 without response body", ProxyIntegrationTests.ProxiesNoContentWithoutBody, TestTaxonomy.Http1),
    Test("Proxy dataplane proxies 304 without response body", ProxyIntegrationTests.ProxiesNotModifiedWithoutBody, TestTaxonomy.Http1),
    Test("Proxy dataplane rejects invalid request framing", ProxyIntegrationTests.RejectsInvalidRequestFraming, TestTaxonomy.Http1, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane rejects malformed chunked request body", ProxyIntegrationTests.RejectsMalformedChunkedRequestBody, TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane filters hop-by-hop request headers", ProxyIntegrationTests.FiltersHopByHopRequestHeaders, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Proxy dataplane preserves Host header", ProxyIntegrationTests.PreservesHostHeader, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Proxy dataplane emits generated response request ID", ProxyIntegrationTests.ResponseIncludesGeneratedRequestId, TestTaxonomy.Http1),
    Test("Proxy dataplane preserves external request ID in diagnostics", ProxyIntegrationTests.ExternalRequestIdIsPreservedInDiagnostics, TestTaxonomy.Http1, TestTaxonomy.Metrics),
    Test("Proxy dataplane records successful diagnostics", ProxyIntegrationTests.SuccessfulRequestProducesDiagnosticRouteAndUpstream, TestTaxonomy.Http1, TestTaxonomy.Metrics),
    Test("Proxy dataplane records upstream connect failure diagnostics", ProxyIntegrationTests.UpstreamConnectFailureProducesDiagnosticClassification, TestTaxonomy.Http1, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane can disable access logs while keeping diagnostics", ProxyIntegrationTests.AccessLoggingCanBeDisabledWhileDiagnosticsRemainEnabled, TestTaxonomy.Http1, TestTaxonomy.Metrics),
    Test("HTTP to HTTPS redirect preserves path and query", ProxyIntegrationTests.HttpToHttpsRedirectPreservesPathAndQuery, TestTaxonomy.Routing, TestTaxonomy.Tls),
    Test("Canonical host redirect works", ProxyIntegrationTests.CanonicalHostRedirectWorks, TestTaxonomy.Routing, TestTaxonomy.Headers),
    Test("Canonical host redirect does not loop", ProxyIntegrationTests.CanonicalHostRedirectDoesNotLoop, TestTaxonomy.Routing, TestTaxonomy.Headers),
    Test("Forwarded headers generated for untrusted direct client", ProxyIntegrationTests.ForwardedHeadersGeneratedForUntrustedDirectClient, TestTaxonomy.Headers),
    Test("Trusted proxy accepts prior forwarded chain", ProxyIntegrationTests.TrustedProxyAcceptsPriorForwardedChain, TestTaxonomy.Config),
    Test("Malformed trusted Forwarded headers are sanitized before upstream", ProxyIntegrationTests.MalformedTrustedForwardedHeadersAreSanitizedBeforeUpstream, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Untrusted client forwarded headers are stripped and replaced", ProxyIntegrationTests.UntrustedClientForwardedHeadersAreStrippedAndReplaced, TestTaxonomy.Headers),
    Test("Request header set/remove rules apply upstream", ProxyIntegrationTests.RequestHeaderSetAndRemoveRulesApplyUpstream, TestTaxonomy.Headers),
    Test("Response header set/remove rules apply downstream", ProxyIntegrationTests.ResponseHeaderSetAndRemoveRulesApplyDownstream, TestTaxonomy.Headers),
    Test("Path prefix stripping preserves query string", ProxyIntegrationTests.PathPrefixStrippingPreservesQueryString, TestTaxonomy.Routing),
    Test("Path prefix replacement works", ProxyIntegrationTests.PathPrefixReplacementWorks, TestTaxonomy.Routing),
    Test("Path rewrite no-match forwards original target", ProxyIntegrationTests.PathRewriteNoMatchForwardsOriginalTarget, TestTaxonomy.Routing),
    Test("Redirect route returns configured redirect", ProxyIntegrationTests.RedirectRouteReturnsConfiguredRedirect, TestTaxonomy.Routing),
    Test("Static response route returns configured response", ProxyIntegrationTests.StaticResponseRouteReturnsConfiguredResponse, TestTaxonomy.Routing),
    Test("Maintenance mode returns 503 and does not contact upstream", ProxyIntegrationTests.MaintenanceModeReturns503AndDoesNotContactUpstream, TestTaxonomy.Routing),
    Test("Per-route body-size override works", ProxyIntegrationTests.PerRouteBodySizeOverrideWorks, TestTaxonomy.Routing),
    Test("Per-route access-log disable is reflected in diagnostics", ProxyIntegrationTests.PerRouteAccessLogDisableIsReflectedInDiagnostics, TestTaxonomy.Routing, TestTaxonomy.Metrics),
    Test("Proxy dataplane records no-route diagnostics and status summary", ProxyIntegrationTests.NoMatchingRouteProducesDiagnosticClassification, TestTaxonomy.Http1, TestTaxonomy.Routing, TestTaxonomy.Metrics),
    Test("Failed reload while proxy active preserves old snapshot and traffic", ProxyIntegrationTests.FailedReloadWhileProxyActivePreservesOldSnapshotAndTraffic, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane rejects oversized request head", ProxyIntegrationTests.OversizedRequestHeadIsRejected, TestTaxonomy.Http1, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane rejects excessive header count", ProxyIntegrationTests.ExcessiveHeaderCountIsRejected, TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane rejects excessive header line", ProxyIntegrationTests.ExcessiveHeaderLineIsRejected, TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane rejects excessive request body size", ProxyIntegrationTests.ExcessiveRequestBodySizeIsRejected, TestTaxonomy.Http1, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/1.1 request body exactly at configured limit is accepted", ProxyIntegrationTests.RequestBodyExactlyAtConfiguredMaxIsAccepted, TestTaxonomy.Http1, TestTaxonomy.Limits),
    Test("HTTP/1.1 chunked request body exactly at configured limit is accepted", ProxyIntegrationTests.ChunkedRequestBodyExactlyAtConfiguredMaxIsAccepted, TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.Limits),
    Test("HTTP/1.1 request body configured limit plus one is rejected", ProxyIntegrationTests.RequestBodyConfiguredMaxPlusOneIsRejected, TestTaxonomy.Http1, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane rejects oversized chunked request body", ProxyIntegrationTests.ChunkedRequestBodySizeIsRejected, TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane enforces per-IP request rate limit", ProxyIntegrationTests.PerIpRequestRateLimitIsEnforced, TestTaxonomy.Http1, TestTaxonomy.Limits),
    Test("Concurrent client admission limit rejects limit plus one and recovers", ProxyIntegrationTests.ConcurrentClientAdmissionLimitRejectsLimitPlusOneAndRecovers, TestTaxonomy.Http1, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Concurrent per-IP rate limit allows only configured boundary", ProxyIntegrationTests.ConcurrentPerIpRateLimitAllowsOnlyConfiguredBoundary, TestTaxonomy.Http1, TestTaxonomy.Limits),
    Test("Proxy dataplane times out incomplete request head", ProxyIntegrationTests.TimesOutIncompleteRequestHead, TestTaxonomy.Http1),
    Test("Proxy dataplane times out incomplete Content-Length request body", ProxyIntegrationTests.TimesOutIncompleteContentLengthRequestBody, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Proxy dataplane times out incomplete chunked request body", ProxyIntegrationTests.TimesOutIncompleteChunkedRequestBody, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("HTTP/1.1 missing terminating chunk times out safely", ProxyIntegrationTests.TimesOutMissingTerminatingChunkAfterCompleteChunk, TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane maps unavailable upstream to 502", ProxyIntegrationTests.UnavailableUpstreamProducesBadGateway, TestTaxonomy.Http1, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane maps upstream response-head timeout to 504", ProxyIntegrationTests.UpstreamResponseHeadTimeoutProducesGatewayTimeout, TestTaxonomy.Http1, TestTaxonomy.RetryCircuit, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Proxy dataplane closes after started response on upstream early close", ProxyIntegrationTests.UpstreamContentLengthEarlyCloseClosesAfterStartedResponse, TestTaxonomy.Http1, TestTaxonomy.UpstreamHttp1),
    Test("HTTP/1.1 upstream chunked early close is contained", ProxyIntegrationTests.UpstreamChunkedEarlyCloseClosesAfterStartedResponse, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("HTTPS listener proxies GET to upstream", ProxyIntegrationTests.HttpsListenerProxiesGetToUpstream, TestTaxonomy.Tls),
    Test("HTTPS listener selects certificate by SNI", ProxyIntegrationTests.HttpsListenerSelectsCertificateBySni, TestTaxonomy.Tls),
    Test("HTTPS listener selects certificate by case-insensitive SNI", ProxyIntegrationTests.HttpsListenerSelectsCertificateByCaseInsensitiveSni, TestTaxonomy.Tls),
    Test("HTTPS listener uses default certificate for unmatched SNI", ProxyIntegrationTests.HttpsListenerUsesDefaultCertificateForUnmatchedSni, TestTaxonomy.Tls),
    Test("HTTPS listener uses default certificate without SNI", ProxyIntegrationTests.HttpsListenerUsesDefaultCertificateWithoutSni, TestTaxonomy.Tls),
    Test("HTTPS listener fails handshake when no certificate matches", ProxyIntegrationTests.HttpsListenerFailsHandshakeWhenNoCertificateMatches, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("HTTPS listener times out incomplete TLS handshake", ProxyIntegrationTests.HttpsListenerTimesOutIncompleteTlsHandshake, TestTaxonomy.Tls),
    Test("Persistent client processes two sequential GETs and reuses upstream", ProxyIntegrationTests.PersistentClientProcessesTwoSequentialGetsAndReusesUpstream, TestTaxonomy.Http1),
    Test("Client Connection close header closes after response", ProxyIntegrationTests.ClientConnectionCloseHeaderClosesAfterResponse, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("HTTP/1.0 client closes by default", ProxyIntegrationTests.Http10ClientClosesByDefault, TestTaxonomy.Http1),
    Test("Max requests per client connection is enforced", ProxyIntegrationTests.MaxRequestsPerClientConnectionIsEnforced, TestTaxonomy.Limits),
    Test("Client keep-alive idle timeout closes connection", ProxyIntegrationTests.ClientKeepAliveIdleTimeoutClosesConnection, TestTaxonomy.Http1, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Malformed second request closes connection", ProxyIntegrationTests.MalformedSecondRequestClosesConnection, TestTaxonomy.Http1, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/1.1 pipelined valid then malformed request does not reach upstream twice", ProxyIntegrationTests.PipelinedValidThenMalformedRequestDoesNotReachUpstreamTwice, TestTaxonomy.Http1, TestTaxonomy.SecurityNegativePaths),
    Test("Persistent client proxies Content-Length POST", ProxyIntegrationTests.PersistentClientProxiesContentLengthPost, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Persistent client proxies chunked POST", ProxyIntegrationTests.PersistentClientProxiesChunkedPost, TestTaxonomy.Http1, TestTaxonomy.Headers),
    Test("Upstream connection is not reused after response Connection close", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterResponseConnectionClose, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Headers),
    Test("Upstream connection is not reused after premature disconnect", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterPrematureDisconnect, TestTaxonomy.UpstreamHttp1),
    Test("Upstream connection is not reused after framing error", ProxyIntegrationTests.UpstreamConnectionIsNotReusedAfterFramingError, TestTaxonomy.UpstreamHttp1),
    Test("WebSocket Upgrade over plaintext returns 101", ProxyIntegrationTests.WebSocketUpgradeOverPlaintextReturnsSwitchingProtocols, TestTaxonomy.Http1),
    Test("WebSocket Upgrade produces tunnel diagnostic", ProxyIntegrationTests.WebSocketUpgradeProducesTunnelDiagnostic, TestTaxonomy.Http1, TestTaxonomy.Metrics),
    Test("WebSocket tunnel relays client bytes upstream", ProxyIntegrationTests.WebSocketTunnelRelaysClientBytesToUpstream, TestTaxonomy.Http1),
    Test("WebSocket tunnel relays upstream bytes client", ProxyIntegrationTests.WebSocketTunnelRelaysUpstreamBytesToClient, TestTaxonomy.Http1),
    Test("WebSocket tunnel closes when client closes", ProxyIntegrationTests.WebSocketTunnelClosesWhenClientCloses, TestTaxonomy.Http1),
    Test("WebSocket tunnel closes when upstream closes", ProxyIntegrationTests.WebSocketTunnelClosesWhenUpstreamCloses, TestTaxonomy.Http1),
    Test("WebSocket tunnel idle timeout closes tunnel", ProxyIntegrationTests.WebSocketTunnelIdleTimeoutClosesTunnel, TestTaxonomy.Http1, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("WebSocket Upgrade over HTTPS returns 101", ProxyIntegrationTests.WebSocketUpgradeOverHttpsReturnsSwitchingProtocols, TestTaxonomy.Http1, TestTaxonomy.Tls),
    Test("Upgrade does not use normal upstream pool", ProxyIntegrationTests.UpgradeDoesNotUseNormalUpstreamPool, TestTaxonomy.Http1, TestTaxonomy.UpstreamHttp1),
    Test("Missing WebSocket headers are rejected", ProxyIntegrationTests.MissingWebSocketHeadersAreRejected, TestTaxonomy.Http1, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream non-101 Upgrade response is forwarded and closed", ProxyIntegrationTests.UpstreamNon101UpgradeResponseIsForwardedAndClosed, TestTaxonomy.Http1),
    Test("Malformed 101 Upgrade response produces bad gateway", ProxyIntegrationTests.MalformedSwitchingProtocolsResponseProducesBadGateway, TestTaxonomy.Http1, TestTaxonomy.SecurityNegativePaths),
    Test("Health check 2xx response is healthy", HealthCheckTests.HealthCheck2xxIsHealthy, TestTaxonomy.HealthChecks),
    Test("Health check 3xx response is healthy", HealthCheckTests.HealthCheck3xxIsHealthy, TestTaxonomy.HealthChecks),
    Test("Health check 4xx response is unhealthy", HealthCheckTests.HealthCheck4xxIsUnhealthy, TestTaxonomy.HealthChecks, TestTaxonomy.SecurityNegativePaths),
    Test("Health check 5xx response is unhealthy", HealthCheckTests.HealthCheck5xxIsUnhealthy, TestTaxonomy.HealthChecks, TestTaxonomy.SecurityNegativePaths),
    Test("Health check timeout is unhealthy", HealthCheckTests.HealthCheckTimeoutIsUnhealthy, TestTaxonomy.HealthChecks, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Health state transitions to unhealthy after threshold", Sync(HealthCheckTests.HealthStateTransitionsToUnhealthyAfterThreshold), TestTaxonomy.HealthChecks, TestTaxonomy.SecurityNegativePaths),
    Test("Health state transitions to healthy after recovery threshold", Sync(HealthCheckTests.HealthStateTransitionsToHealthyAfterRecoveryThreshold), TestTaxonomy.HealthChecks),
    Test("Health check coordinator records due checks and metrics", HealthCheckTests.HealthCheckCoordinatorRunsDueChecksAndRecordsMetrics, TestTaxonomy.HealthChecks, TestTaxonomy.Metrics),
    Test("Health check coordinator skips until interval elapses", HealthCheckTests.HealthCheckCoordinatorSkipsUntilIntervalElapses, TestTaxonomy.HealthChecks),
    Test("Round-robin distributes sequential requests across two upstreams", ProxyIntegrationTests.RoundRobinDistributesSequentialRequestsAcrossTwoUpstreams, TestTaxonomy.Routing),
    Test("Unhealthy upstream is not selected", ProxyIntegrationTests.UnhealthyUpstreamIsNotSelected, TestTaxonomy.HealthChecks, TestTaxonomy.SecurityNegativePaths),
    Test("All unhealthy upstreams return service unavailable", ProxyIntegrationTests.AllUnhealthyUpstreamsReturnServiceUnavailable, TestTaxonomy.RetryCircuit, TestTaxonomy.HealthChecks, TestTaxonomy.SecurityNegativePaths),
    Test("WebSocket Upgrade uses round-robin upstream selection", ProxyIntegrationTests.WebSocketUpgradeUsesRoundRobinUpstreamSelection, TestTaxonomy.Http1, TestTaxonomy.Routing),
    Test("Upstream pool uses distinct endpoint keys", ProxyIntegrationTests.UpstreamPoolUsesDistinctEndpointKeys, TestTaxonomy.UpstreamHttp1),
    ];
}
