namespace MDRAVA.Tests;

internal static partial class TestRegistry
{
    private static TestCase[] OperatorRuntimeAndLimits() =>
    [
    Test("Recent diagnostics store is bounded", Sync(ObservabilityTests.RecentDiagnosticsStoreIsBounded), TestTaxonomy.Limits, TestTaxonomy.Metrics),
    Test("Diagnostics controller honors safe limit", Sync(ObservabilityTests.DiagnosticsControllerHonorsSafeLimit), TestTaxonomy.Limits, TestTaxonomy.Metrics),
    Test("Request diagnostics reader returns recent events from source", Sync(ObservabilityTests.RequestDiagnosticsReaderReturnsRecentEventsFromSource), TestTaxonomy.Metrics),
    Test("Diagnostics event omits bodies and secrets", Sync(ObservabilityTests.DiagnosticsEventDoesNotCarryBodiesOrSecrets), TestTaxonomy.Metrics),
    Test("External request ID policy normalizes safe header values", Sync(ObservabilityTests.ExternalRequestIdPolicyNormalizesSafeHeaderValues), TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Request ID generator creates distinct IDs and records metric", Sync(ObservabilityTests.RequestIdGeneratorCreatesDistinctIdsAndRecordsMetric), TestTaxonomy.Metrics),
    Test("Access log persistence writes redacted JSON line", Sync(LogPersistenceTests.AccessLogPersistenceWritesRedactedJsonLine), TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Access log persistence honors access log disable", Sync(LogPersistenceTests.AccessLogPersistenceHonorsAccessLogDisable), TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Admin audit persistence writes failed auth without secrets", LogPersistenceTests.AdminAuditPersistenceWritesFailedAuthWithoutSecrets, TestTaxonomy.Admin, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Log persistence creates logs directory", Sync(LogPersistenceTests.LogPersistenceCreatesLogsDirectory), TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Log persistence rotates and bounds files", Sync(LogPersistenceTests.LogPersistenceRotatesAndBoundsFiles), TestTaxonomy.Limits, TestTaxonomy.Metrics),
    Test("Log persistence truncates long fields", Sync(LogPersistenceTests.LogPersistenceTruncatesLongFields), TestTaxonomy.Limits, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Log persistence write failure does not crash", Sync(LogPersistenceTests.LogPersistenceWriteFailureDoesNotCrash), TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Log persistence status reports enabled settings", Sync(LogPersistenceTests.LogPersistenceStatusReportsEnabledSettings), TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Log persistence settings mapper reads runtime options without configuration snapshot", Sync(LogPersistenceTests.LogPersistenceSettingsMapperReadsRuntimeOptionsWithoutConfigurationSnapshot), TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Log persistence settings reader uses named disabled defaults when source missing", Sync(LogPersistenceTests.LogPersistenceSettingsReaderUsesNamedDisabledDefaultsWhenSourceMissing), TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Log persistence status reports disabled settings", Sync(LogPersistenceTests.LogPersistenceStatusReportsDisabledSettings), TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Log persistence status records last write failure without secrets", Sync(LogPersistenceTests.LogPersistenceStatusRecordsLastWriteFailureWithoutSecrets), TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Status controller includes log persistence health without secrets", Sync(LogPersistenceTests.StatusControllerIncludesLogPersistenceHealthWithoutSecrets), TestTaxonomy.Admin, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Status input reader assembles named input from sources", Sync(OperatorStatusTests.StatusInputReaderAssemblesNamedInputFromSources), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Status upstream health reader consumes configured health sources without runtime routes", Sync(OperatorStatusTests.StatusUpstreamHealthReaderConsumesConfiguredHealthSourcesWithoutRuntimeRoutes), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status runtime summary mapper projects response runtime facts", Sync(OperatorStatusTests.StatusRuntimeSummaryMapperProjectsOnlyResponseRuntimeFacts), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status runtime source reads runtime summary without runtime snapshot", Sync(OperatorStatusTests.StatusRuntimeSourceReadsRuntimeSummaryWithoutRuntimeSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Runtime state copies listener lists on write and read", Sync(OperatorStatusTests.RuntimeStateCopiesListenerListsOnWriteAndRead), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status configuration summary mapper reads runtime configuration facts without snapshot", Sync(OperatorStatusTests.StatusConfigurationSummaryMapperReadsRuntimeConfigurationFactsWithoutSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status configuration source mapper shapes status facts from active configuration", Sync(OperatorStatusTests.StatusConfigurationSourceMapperShapesStatusFactsFromActiveConfiguration), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status response builder builds response from named input", Sync(OperatorStatusTests.StatusResponseBuilderBuildsResponseFromNamedInput), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Status readiness reports healthy for active snapshot", Sync(OperatorStatusTests.StatusReadinessReportsHealthyForActiveSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Caching, TestTaxonomy.Metrics),
    Test("Status readiness source mapper consumes runtime summary without runtime snapshot", Sync(OperatorStatusTests.StatusReadinessSourceMapperConsumesRuntimeSummaryWithoutRuntimeSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status readiness configuration source set names missing configuration", Sync(OperatorStatusTests.StatusReadinessConfigurationSourceSetNamesMissingConfiguration), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status readiness source mapper consumes configuration source set without configuration snapshot", Sync(OperatorStatusTests.StatusReadinessSourceMapperConsumesConfigurationSourceSetWithoutConfigurationSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status listener and route source mappers read collections without configuration snapshot", Sync(OperatorStatusTests.StatusListenerAndRouteSourceMappersReadCollectionsWithoutConfigurationSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status ACME summary configuration mapper reads ACME options without configuration snapshot", Sync(OperatorStatusTests.StatusAcmeSummaryConfigurationMapperReadsAcmeOptionsWithoutConfigurationSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status certificate summary source mapper reads listeners and certificates without snapshot", Sync(OperatorStatusTests.StatusCertificateSummarySourceMapperReadsListenersAndCertificatesWithoutSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Status limit summary configuration mapper reads limits without configuration snapshot", Sync(OperatorStatusTests.StatusLimitSummaryConfigurationMapperReadsLimitsWithoutConfigurationSnapshot), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Limits),
    Test("Readiness evaluator consumes narrow facts without runtime snapshots", Sync(OperatorStatusTests.ReadinessEvaluatorConsumesNarrowFactsWithoutRuntimeSnapshots), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Status readiness builder consumes named facts without runtime snapshots", Sync(OperatorStatusTests.StatusReadinessBuilderConsumesNamedFactsWithoutRuntimeSnapshots), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Subsystem summary builder counts narrow listener route and upstream sources", Sync(OperatorStatusTests.SubsystemSummaryBuilderCountsNarrowListenerRouteAndUpstreamSources), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Subsystem summary builder classifies certificate issues from narrow sources", Sync(OperatorStatusTests.SubsystemSummaryBuilderClassifiesCertificateIssuesFromNarrowSources), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Status readiness reports log persistence failure as degraded", Sync(OperatorStatusTests.StatusReadinessReportsLogPersistenceFailureAsDegraded), TestTaxonomy.Admin, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Status readiness reports no active listener as not ready", Sync(OperatorStatusTests.StatusReadinessReportsNoActiveListenerAsNotReady), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Status readiness reports failed listener reload without losing active config", Sync(OperatorStatusTests.StatusReadinessReportsFailedListenerReloadWithoutLosingActiveConfig), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Status readiness summarizes unhealthy upstreams", Sync(OperatorStatusTests.StatusReadinessSummarizesUnhealthyUpstreams), TestTaxonomy.Admin, TestTaxonomy.HealthChecks, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Status readiness summarizes open circuits", Sync(OperatorStatusTests.StatusReadinessSummarizesOpenCircuits), TestTaxonomy.Admin, TestTaxonomy.RetryCircuit, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Status subsystems keep unsupported HTTP/3 features explicit", Sync(OperatorStatusTests.StatusSubsystemsKeepUnsupportedHttp3FeaturesExplicit), TestTaxonomy.Admin, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("Status readiness reports certificate issue summary without secrets", Sync(OperatorStatusTests.StatusReadinessReportsCertificateIssueSummaryWithoutSecrets), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Status readiness reports ACME last issue without raw error summary", Sync(OperatorStatusTests.StatusReadinessReportsAcmeLastIssueWithoutRawErrorSummary), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Status readiness reports runtime preflight warnings without secrets", Sync(OperatorStatusTests.StatusReadinessReportsRuntimePreflightWarningsWithoutSecrets), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Backup manifest classifies data directory without file contents or secrets", Sync(BackupRestoreTests.BackupManifestClassifiesDataDirectoryWithoutFileContentsOrSecrets), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Backup manifest reports missing directories with bounded warnings", Sync(BackupRestoreTests.BackupManifestReportsMissingDirectoriesWithBoundedWarnings), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Backup manifest builder truncates and counts bounded entries", Sync(BackupRestoreTests.BackupManifestBuilderTruncatesAndCountsBoundedEntries), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Limits),
    Test("Backup manifest entry factory classifies filesystem entry", Sync(BackupRestoreTests.BackupManifestEntryFactoryClassifiesFilesystemEntry), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Backup file system scan result names missing root and scanned outcomes", Sync(BackupRestoreTests.BackupFileSystemScanResultNamesMissingRootAndScannedOutcomes), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Restore validation directory policy reports only missing required directories", Sync(BackupRestoreTests.RestoreValidationDirectoryPolicyReportsOnlyMissingRequiredDirectories), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Restore validation finding policy builds configuration error findings", Sync(BackupRestoreTests.RestoreValidationFindingPolicyBuildsConfigurationErrorFindings), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Restore validation response builder bounds findings and requires no errors", Sync(BackupRestoreTests.RestoreValidationResponseBuilderBoundsFindingsAndRequiresNoErrors), TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Limits),
    Test("Backup and restore results copy input collections", Sync(BackupRestoreTests.BackupAndRestoreResultsCopyInputCollections), TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Backup path safety rejects traversal outside data directory", Sync(BackupRestoreTests.BackupPathSafetyRejectsTraversalOutsideDataDirectory), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Restore validation catches invalid config without creating bootstrap files", BackupRestoreTests.RestoreValidationCatchesInvalidConfigWithoutCreatingBootstrapFiles, TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Restore validation catches missing referenced certificate material", BackupRestoreTests.RestoreValidationCatchesMissingReferencedCertificateMaterial, TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Restore validation preserves existing active runtime state", BackupRestoreTests.RestoreValidationPreservesExistingActiveRuntimeState, TestTaxonomy.Admin, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Restore validation succeeds with bootstrap layout", BackupRestoreTests.RestoreValidationSucceedsWithBootstrapLayout, TestTaxonomy.Admin, TestTaxonomy.Config),
    Test("Runtime preflight creates owned directories safely", Sync(RuntimePreflightTests.RuntimePreflightCreatesOwnedDirectoriesSafely), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Runtime preflight reports unwritable directory safely", Sync(RuntimePreflightTests.RuntimePreflightReportsUnwritableDirectorySafely), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Runtime preflight rejects unsafe child path", Sync(RuntimePreflightTests.RuntimePreflightRejectsUnsafeChildPath), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Runtime preflight inspect does not create missing directories", Sync(RuntimePreflightTests.RuntimePreflightInspectDoesNotCreateMissingDirectories), TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Runtime preflight probe policy classifies reason and severity", Sync(RuntimePreflightTests.RuntimePreflightProbePolicyClassifiesReasonAndSeverity), TestTaxonomy.Config),
    Test("Runtime directory probe result names common outcomes", Sync(RuntimePreflightTests.RuntimeDirectoryProbeResultNamesCommonOutcomes), TestTaxonomy.Config),
    Test("Runtime preflight directory policy lists expected directories", Sync(RuntimePreflightTests.RuntimePreflightDirectoryPolicyListsExpectedDirectories), TestTaxonomy.Config),
    Test("Runtime preflight status builder builds state and bounded reasons", Sync(RuntimePreflightTests.RuntimePreflightStatusBuilderBuildsStateAndBoundedReasons), TestTaxonomy.Config),
    Test("Runtime preflight check factory builds unsafe and probed checks", Sync(RuntimePreflightTests.RuntimePreflightCheckFactoryBuildsUnsafeAndProbedChecks), TestTaxonomy.Config),
    Test("Admission controller enforces client limit", Sync(HardeningTests.AdmissionControllerEnforcesClientLimit), TestTaxonomy.Limits),
    Test("Admission lease disposal releases client slot", Sync(HardeningTests.AdmissionLeaseDisposalReleasesClientSlot), TestTaxonomy.Limits),
    Test("Admission controller enforces TLS handshake limit", Sync(HardeningTests.AdmissionControllerEnforcesTlsHandshakeLimit), TestTaxonomy.Tls, TestTaxonomy.Limits),
    Test("Admission lease disposal releases TLS handshake slot", Sync(HardeningTests.AdmissionLeaseDisposalReleasesTlsHandshakeSlot), TestTaxonomy.Tls, TestTaxonomy.Limits),
    Test("Client address policy normalizes client IP addresses", Sync(ProxyClientAddressPolicyTests.NormalizesClientIpAddresses), TestTaxonomy.Limits, TestTaxonomy.Admin),
    Test("Rate limiter enforces request limit and refill", Sync(HardeningTests.RateLimiterEnforcesRequestLimitAndRefills), TestTaxonomy.Limits),
    Test("Concurrent rate limiter boundary allows only configured limit", Sync(HardeningTests.ConcurrentRateLimiterBoundaryAllowsOnlyConfiguredLimit), TestTaxonomy.Limits),
    Test("Rate limiter enforces upgrade limit", Sync(HardeningTests.RateLimiterEnforcesUpgradeLimit), TestTaxonomy.Limits),
    Test("Rate limiter uses normalized client address keys", Sync(HardeningTests.RateLimiterUsesNormalizedClientAddressKeys), TestTaxonomy.Limits),
    Test("Rate limiter cleans stale entries", Sync(HardeningTests.RateLimiterCleansStaleEntries), TestTaxonomy.Limits),
    Test("Shutdown coordinator exposes grace deadline", Sync(HardeningTests.ShutdownCoordinatorExposesGraceDeadlineAndCancels), TestTaxonomy.Limits),
    Test("Shutdown coordinator begin shutdown is idempotent", Sync(HardeningTests.ShutdownCoordinatorBeginShutdownIsIdempotent), TestTaxonomy.Limits)
    ];
}
