namespace MDRAVA.Tests;

internal static partial class TestRegistry
{
    private static TestCase[] Http2AndHttp3() =>
    [
    Test("HTTP/2 client preserves HTTP/1.1 behavior", ClientHttp2Tests.ExistingHttp1BehaviorRemainsUnchanged, TestTaxonomy.Http1, TestTaxonomy.Http2),
    Test("HTTP/2 plaintext listener is rejected", Sync(ClientHttp2Tests.PlaintextHttp2ListenerIsRejected), TestTaxonomy.Http2, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 ALPN selects h2 when enabled", ClientHttp2Tests.AlpnSelectsHttp2WhenEnabled, TestTaxonomy.Http2, TestTaxonomy.Tls),
    Test("HTTP/2 request maps to route matcher", ClientHttp2Tests.Http2RequestMapsToRouteMatcher, TestTaxonomy.Http2, TestTaxonomy.Routing),
    Test("HTTP/2 authority maps to host routing", ClientHttp2Tests.AuthorityMapsToHostRouting, TestTaxonomy.Http2, TestTaxonomy.Headers, TestTaxonomy.Admin),
    Test("HTTP/2 query string is preserved", ClientHttp2Tests.QueryStringIsPreserved, TestTaxonomy.Http2),
    Test("HTTP/2 invalid pseudo headers are rejected", ClientHttp2Tests.InvalidPseudoHeadersAreRejected, TestTaxonomy.Http2, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 forbidden connection headers are rejected", ClientHttp2Tests.ForbiddenConnectionHeadersAreRejected, TestTaxonomy.Http2, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 Huffman request header values are decoded", ClientHttp2Tests.HuffmanRequestHeaderValuesAreDecoded, TestTaxonomy.Http2, TestTaxonomy.Headers),
    Test("HTTP/2 response omits hop-by-hop headers", ClientHttp2Tests.ResponseOmitsHopByHopHeaders, TestTaxonomy.Http2, TestTaxonomy.Headers),
    Test("HTTP/2 static response route works", ClientHttp2Tests.StaticResponseRouteWorksOverHttp2, TestTaxonomy.Http2, TestTaxonomy.Routing),
    Test("Active HTTP/2 traffic survives certificate reload and new connections use reloaded certificate", ClientHttp2Tests.ActiveHttp2TrafficSurvivesCertificateReloadAndNewConnectionsUseReloadedCertificate, TestTaxonomy.Http2, TestTaxonomy.Tls),
    Test("Failed HTTP/2 certificate reload preserves previous active certificate", ClientHttp2Tests.FailedHttp2CertificateReloadPreservesPreviousActiveCertificate, TestTaxonomy.Http2, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 redirect route works", ClientHttp2Tests.RedirectRouteWorksOverHttp2, TestTaxonomy.Http2, TestTaxonomy.Routing),
    Test("HTTP/2 maintenance route works", ClientHttp2Tests.MaintenanceRouteWorksOverHttp2, TestTaxonomy.Http2, TestTaxonomy.Routing),
    Test("HTTP/2 HEAD returns no body", ClientHttp2Tests.HeadReturnsHeadersWithoutBody, TestTaxonomy.Http2),
    Test("HTTP/2 cache works", ClientHttp2Tests.CacheWorksOverHttp2, TestTaxonomy.Http2, TestTaxonomy.Caching),
    Test("HTTP/2 retry works for proxy requests", ClientHttp2Tests.RetryWorksForHttp2ProxyRequests, TestTaxonomy.Http2, TestTaxonomy.RetryCircuit),
    Test("HTTP/2 extended CONNECT is rejected", ClientHttp2Tests.ExtendedConnectIsRejected, TestTaxonomy.Http2, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 concurrent streams reach different routes", ClientHttp2Tests.ConcurrentStreamsReachDifferentRoutes, TestTaxonomy.Http2, TestTaxonomy.Routing),
    Test("HTTP/2 DATA before HEADERS is rejected safely", ClientHttp2Tests.DataBeforeHeadersIsRejectedSafely, TestTaxonomy.Http2, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 CONTINUATION header fragmentation is accepted", ClientHttp2Tests.ContinuationHeaderFragmentationIsAccepted, TestTaxonomy.Http2, TestTaxonomy.Headers),
    Test("HTTP/2 RST_STREAM releases state and keeps connection usable", ClientHttp2Tests.RstStreamReleasesStateAndKeepsConnectionUsable, TestTaxonomy.Http2),
    Test("HTTP/2 GOAWAY stops new streams safely", ClientHttp2Tests.GoAwayStopsNewStreamsSafely, TestTaxonomy.Http2),
    Test("HTTP/2 oversized header list is rejected", ClientHttp2Tests.OversizedHeaderListIsRejected, TestTaxonomy.Http2, TestTaxonomy.Headers, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 metrics include counters", ClientHttp2Tests.MetricsIncludeHttp2Counters, TestTaxonomy.Http2, TestTaxonomy.Metrics),
    Test("Upstream HTTP/2 preserves HTTP/1.1 upstream default", UpstreamHttp2Tests.ExistingHttp1UpstreamProtocolRemainsDefault, TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2),
    Test("Upstream HTTP/2 requires HTTPS", Sync(UpstreamHttp2Tests.Http2UpstreamRequiresHttps), TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.Tls),
    Test("Unsupported upstream protocol is rejected", Sync(UpstreamHttp2Tests.UnsupportedUpstreamProtocolIsRejected), TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream pool key differs for HTTP/1.1 and HTTP/2", Sync(UpstreamHttp2Tests.PoolKeyDiffersForHttp1AndHttp2), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2),
    Test("Upstream HTTP/2 advertises h2 ALPN", UpstreamHttp2Tests.UpstreamAlpnAdvertisesHttp2, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.Tls),
    Test("Upstream HTTP/2 ALPN failure does not fallback", UpstreamHttp2Tests.AlpnFailureDoesNotFallbackToHttp1, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream HTTP/2 proxy maps headers query and response", UpstreamHttp2Tests.Http2UpstreamProxyMapsHeadersQueryAndResponse, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.Headers),
    Test("Upstream HTTP/2 forwards request body", UpstreamHttp2Tests.Http2UpstreamForwardsRequestBody, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2),
    Test("Upstream HTTP/2 ends zero-length request body", UpstreamHttp2Tests.Http2UpstreamEndsZeroLengthRequestBody, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2),
    Test("Cache works with HTTP/2 upstream", UpstreamHttp2Tests.CacheWorksWithHttp2Upstream, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.Caching),
    Test("HTTP/2 upstream health check uses h2 and rejects wrong ALPN", UpstreamHttp2Tests.Http2HealthCheckUsesH2AndRejectsWrongAlpn, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.Tls, TestTaxonomy.HealthChecks, TestTaxonomy.SecurityNegativePaths),
    Test("Metrics include upstream HTTP/2 counters", UpstreamHttp2Tests.MetricsIncludeUpstreamHttp2Counters, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.Metrics),
    Test("HTTP/2 upstream close before response headers returns safe failure", UpstreamHttp2Tests.Http2UpstreamCloseBeforeResponseHeadersReturnsSafeFailure, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/2 upstream close after response headers does not retry after headers are sent", UpstreamHttp2Tests.Http2UpstreamCloseAfterResponseHeadersDoesNotRetryAfterHeadersAreSent, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.RetryCircuit),
    Test("HTTP/2 streaming POST body is not retried after upstream failure", UpstreamHttp2Tests.Http2StreamingPostBodyIsNotRetriedAfterUpstreamFailure, TestTaxonomy.Http2, TestTaxonomy.UpstreamHttp2, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream HTTP/3 requires HTTPS", Sync(UpstreamHttp3Tests.Http3UpstreamRequiresHttps), TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Tls),
    Test("Upstream HTTP/3 config parses and validates", UpstreamHttp3Tests.Http3UpstreamConfigParsesAndValidates, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Upstream HTTP/3 effective projection reports reused multiplexed pooling", UpstreamHttp3Tests.Http3EffectiveProjectionReportsReusedMultiplexedPooling, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Config),
    Test("Upstream pool key differs for HTTP/1.1 HTTP/2 and HTTP/3", Sync(UpstreamHttp3Tests.PoolKeyDiffersForHttp1Http2AndHttp3), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Upstream HTTP/3 pool key includes SNI and validation", Sync(UpstreamHttp3Tests.PoolKeyIncludesHttp3SniAndValidation), TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Tls),
    Test("Upstream HTTP/3 proxy maps headers query and response", UpstreamHttp3Tests.Http3UpstreamProxyMapsHeadersQueryAndResponse, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Headers),
    Test("Sequential upstream HTTP/3 requests reuse a pooled connection", UpstreamHttp3Tests.SequentialHttp3UpstreamRequestsReuseConnection, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Concurrent upstream HTTP/3 requests share a pooled connection", UpstreamHttp3Tests.ConcurrentHttp3UpstreamRequestsShareConnection, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Idle upstream HTTP/3 pooled connections expire", UpstreamHttp3Tests.IdleHttp3UpstreamConnectionsExpire, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Upstream HTTP/3 GOAWAY drains connection without breaking active stream", UpstreamHttp3Tests.UpstreamHttp3GoAwayDrainsConnectionWithoutBreakingActiveStream, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Upstream HTTP/3 pool stream-limit exhaustion returns safe failure", UpstreamHttp3Tests.UpstreamHttp3PoolStreamLimitExhaustionReturnsSafeFailure, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream HTTP/3 concurrent reuse releases active stream gauge", UpstreamHttp3Tests.ConcurrentHttp3UpstreamReuseReleasesActiveStreamGauge, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Upstream HTTP/3 stream reset does not poison unrelated active stream", UpstreamHttp3Tests.UpstreamHttp3StreamResetDoesNotPoisonUnrelatedActiveStream, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Upstream HTTP/3 failed connection does not receive new streams", UpstreamHttp3Tests.FailedHttp3UpstreamConnectionDoesNotReceiveNewStreams, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream HTTP/3 ALPN failure does not downgrade", UpstreamHttp3Tests.Http3UpstreamAlpnFailureDoesNotDowngrade, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream HTTP/3 malformed response headers are rejected", UpstreamHttp3Tests.Http3UpstreamMalformedResponseHeadersAreRejected, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream HTTP/3 forwards request body", UpstreamHttp3Tests.Http3UpstreamForwardsRequestBody, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3),
    Test("Upstream HTTP/3 health check uses h3", UpstreamHttp3Tests.Http3HealthCheckUsesH3, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.HealthChecks),
    Test("Cache works with HTTP/3 upstream", UpstreamHttp3Tests.CacheWorksWithHttp3Upstream, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Caching),
    Test("Metrics include upstream HTTP/3 counters", UpstreamHttp3Tests.MetricsIncludeUpstreamHttp3Counters, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Metrics),
    Test("HTTP/3 upstream close before response headers returns safe failure", UpstreamHttp3Tests.Http3UpstreamCloseBeforeResponseHeadersReturnsSafeFailure, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 upstream close after response headers releases stream slot", UpstreamHttp3Tests.Http3UpstreamCloseAfterResponseHeadersReleasesStreamSlot, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.RetryCircuit),
    Test("HTTP/3 streaming POST body is not retried after upstream failure", UpstreamHttp3Tests.Http3StreamingPostBodyIsNotRetriedAfterUpstreamFailure, TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Existing HTTP/1.1 and HTTP/2 listener protocols still validate", Sync(Http3InfrastructureTests.ExistingHttp1AndHttp2ProtocolsStillValidate), TestTaxonomy.Http1, TestTaxonomy.Http2, TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("Listener protocol config parsing uses current HTTP/3 spellings", Sync(Http3InfrastructureTests.ListenerProtocolConfigParsingUsesCurrentHttp3Spellings), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("HTTP/3 compatibility normalizer centralizes enablement semantics", Sync(Http3InfrastructureTests.Http3CompatibilityNormalizerCentralizesEnablementSemantics), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("Current HTTP/3 config validates maps and aggregates consistently", Sync(Http3InfrastructureTests.CurrentHttp3ConfigValidatesMapsAndAggregatesConsistently), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("Legacy HTTP/3 config aliases are rejected", Sync(Http3InfrastructureTests.LegacyHttp3ConfigAliasesAreRejected), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Removed HTTP/3 config properties are rejected by parser", Sync(Http3InfrastructureTests.RemovedHttp3ConfigPropertiesAreRejectedByParser), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 defaults on for eligible TLS listeners", Sync(Http3InfrastructureTests.Http3DefaultEnabledForEligibleTlsListener), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("HTTP/3 defaults off for plaintext listeners", Sync(Http3InfrastructureTests.Http3DefaultDisabledForPlaintextListener), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("HTTP/3 protocol uses default enablement", Sync(Http3InfrastructureTests.Http3ProtocolUsesDefaultEnablement), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.Admin),
    Test("HTTP/3 protocol requires TLS certificate capable listener", Sync(Http3InfrastructureTests.Http3RequiresTlsCertificateCapableListener), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.Admin),
    Test("HTTP/3 config enables traffic", Sync(Http3InfrastructureTests.Http3ConfigEnablesTraffic), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("HTTP/3-only config does not enable TCP traffic", Sync(Http3InfrastructureTests.Http3OnlyDoesNotEnableTcpTraffic), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("TCP listener identity remains unchanged", Sync(Http3InfrastructureTests.TcpListenerIdentityRemainsUnchanged), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("QUIC listener identity is separate from TCP identity", Sync(Http3InfrastructureTests.QuicListenerIdentityIsSeparateFromTcpIdentity), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("TCP ALPN does not advertise HTTP/3", Sync(Http3InfrastructureTests.TcpAlpnDoesNotAdvertiseHttp3), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Status and effective projection report HTTP/3 enabled", Sync(Http3InfrastructureTests.StatusAndEffectiveProjectionReportHttp3Enabled), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("Final HTTP/3 support projection reports matrix and final naming", Sync(Http3InfrastructureTests.FinalSupportProjectionReportsHttp3MatrixAndFinalNaming), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("HTTP/3 upstream protocol accepts explicit config", Sync(Http3InfrastructureTests.UpstreamProtocolAcceptsExplicitHttp3), TestTaxonomy.Http3, TestTaxonomy.UpstreamHttp3, TestTaxonomy.Config),
    Test("HTTP/3 defaults on for eligible TLS runtime listener", Sync(ClientHttp3Tests.Http3DefaultEnabledForEligibleTlsListener), TestTaxonomy.Http3, TestTaxonomy.Tls),
    Test("Explicit HTTP/3 disable prevents traffic", Sync(ClientHttp3Tests.ExplicitHttp3DisablePreventsTraffic), TestTaxonomy.Http3),
    Test("HTTP/3 QUIC listener identity is separate from TCP identity", Sync(ClientHttp3Tests.QuicListenerIdentityIsSeparateFromTcpIdentity), TestTaxonomy.Http3),
    Test("Failed HTTP/3 QUIC listener start does not break TCP listener", ClientHttp3Tests.FailedQuicListenerStartDoesNotBreakTcpListener, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("Default HTTP/3 TLS listener starts QUIC and emits Alt-Svc", ClientHttp3Tests.DefaultHttp3TlsListenerStartsQuicAndEmitsAltSvc, TestTaxonomy.Http3, TestTaxonomy.Tls),
    Test("Successful reload can add and remove HTTP/3 QUIC listener", ClientHttp3Tests.SuccessfulReloadCanAddAndRemoveQuicListener, TestTaxonomy.Http3),
    Test("Failed reload preserves old HTTP/3 listener set", ClientHttp3Tests.FailedReloadPreservesOldQuicListenerSet, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("Successful HTTP/3 certificate reload keeps QUIC listener and uses new certificate", ClientHttp3Tests.SuccessfulHttp3CertificateReloadKeepsQuicListenerAndUsesNewCertificate, TestTaxonomy.Http3, TestTaxonomy.Tls),
    Test("Failed HTTP/3 certificate reload preserves previous QUIC certificate", ClientHttp3Tests.FailedHttp3CertificateReloadPreservesPreviousQuicCertificate, TestTaxonomy.Http3, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Status and effective config use current HTTP/3 projection", Sync(ClientHttp3Tests.StatusAndEffectiveConfigUseCurrentHttp3Projection), TestTaxonomy.Http3, TestTaxonomy.Config),
    Test("HTTP/3 legacy enablement values are rejected", Sync(ClientHttp3Tests.Http3LegacyEnablementValuesAreRejected), TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 Alt-Svc policy reads narrow runtime listener source", Sync(ClientHttp3Tests.AltSvcPolicyReadsNarrowRuntimeListenerSource), TestTaxonomy.Http3),
    Test("HTTP/3 Alt-Svc policy applies emitted headers", Sync(ClientHttp3Tests.AltSvcPolicyAppliesHeaderWithoutKeepingStaleValues), TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("HTTP/3 Alt-Svc is absent when HTTP/3 is explicitly disabled", ClientHttp3Tests.AltSvcIsAbsentWhenHttp3ExplicitlyDisabled, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 Alt-Svc is emitted only when configured and ready", ClientHttp3Tests.AltSvcIsEmittedOnlyWhenConfiguredAndReady, TestTaxonomy.Http3),
    Test("HTTP/3 Alt-Svc is not emitted when QUIC listener is not ready", ClientHttp3Tests.AltSvcIsNotEmittedWhenQuicListenerIsNotReady, TestTaxonomy.Http3),
    Test("Admin responses do not emit HTTP/3 Alt-Svc", Sync(ClientHttp3Tests.AdminResponsesDoNotEmitAltSvc), TestTaxonomy.Http3, TestTaxonomy.Admin),
    Test("Minimal HTTP/3 GET can reach generated route", ClientHttp3Tests.MinimalHttp3GetCanReachGeneratedRoute, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 HEAD returns headers without body", ClientHttp3Tests.HeadReturnsHeadersWithoutBody, TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("HTTP/3 generated redirect route works", ClientHttp3Tests.Http3GeneratedRedirectRouteWorks, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 generated maintenance route works", ClientHttp3Tests.Http3GeneratedMaintenanceRouteWorks, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 route miss returns safe 404", ClientHttp3Tests.Http3RouteMissReturnsSafe404, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 route miss remains stable across repeated ready-listener requests", ClientHttp3Tests.Http3RouteMissRemainsStableAcrossRepeatedReadyListenerRequests, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 GET proxy route works", ClientHttp3Tests.Http3GetProxyRouteWorks, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 HEAD proxy route works", ClientHttp3Tests.Http3HeadProxyRouteWorks, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 proxy preserves query string", ClientHttp3Tests.Http3ProxyPreservesQueryString, TestTaxonomy.Http3),
    Test("HTTP/3 proxy strips pseudo headers before upstream", ClientHttp3Tests.Http3ProxyStripsPseudoHeadersBeforeUpstream, TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("HTTP/3 response headers are encoded safely", ClientHttp3Tests.Http3ResponseHeadersAreEncodedSafely, TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("HTTP/3 chunked response streams body without Transfer-Encoding", ClientHttp3Tests.Http3ChunkedResponseStreamsBodyWithoutTransferEncoding, TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("HTTP/3 response streams before upstream completes", ClientHttp3Tests.Http3ResponseStreamsBeforeUpstreamCompletes, TestTaxonomy.Http3),
    Test("HTTP/3 cache interaction uses stored response", ClientHttp3Tests.Http3CacheInteractionUsesStoredResponse, TestTaxonomy.Http3, TestTaxonomy.Caching),
    Test("HTTP/3 oversized cache candidate streams but is not cached", ClientHttp3Tests.Http3OversizedCacheCandidateStreamsButIsNotCached, TestTaxonomy.Http3, TestTaxonomy.Caching, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 retry for GET can reach second upstream", ClientHttp3Tests.Http3RetryForGetCanReachSecondUpstream, TestTaxonomy.Http3, TestTaxonomy.RetryCircuit),
    Test("HTTP/3 unsupported CONNECT is rejected", ClientHttp3Tests.UnsupportedConnectIsRejected, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 malformed CONNECT is rejected", ClientHttp3Tests.MalformedHttp3ConnectIsRejected, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 extended CONNECT WebSocket form is rejected", ClientHttp3Tests.ExtendedHttp3ConnectWebSocketIsRejected, TestTaxonomy.Http1, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 POST with bounded body reaches upstream", ClientHttp3Tests.Http3PostWithBoundedBodyReachesUpstream, TestTaxonomy.Http3, TestTaxonomy.Limits),
    Test("HTTP/3 PUT PATCH and DELETE bodies reach upstream", ClientHttp3Tests.Http3PutPatchAndDeleteBodiesReachUpstream, TestTaxonomy.Http3),
    Test("HTTP/3 path rewrite applies to proxy route", ClientHttp3Tests.Http3PathRewriteAppliesToProxyRoute, TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("HTTP/3 body size limit applies", ClientHttp3Tests.Http3BodySizeLimitApplies, TestTaxonomy.Http3, TestTaxonomy.Limits),
    Test("Removed HTTP/3 buffered request body limit is rejected by parser", Sync(ClientHttp3Tests.RemovedHttp3BufferedRequestBodyLimitIsRejectedByParser), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 request with body is not retried", ClientHttp3Tests.Http3RequestWithBodyIsNotRetried, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 invalid frame sequence is rejected", ClientHttp3Tests.InvalidFrameSequenceIsRejected, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 unexpected control frame on request stream is rejected", ClientHttp3Tests.UnexpectedControlFrameOnRequestStreamIsRejected, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 GOAWAY frame on request stream is rejected", ClientHttp3Tests.GoAwayFrameOnRequestStreamIsRejected, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 duplicate HEADERS after request headers are rejected", ClientHttp3Tests.DuplicateHeadersAfterHeadersIsRejected, TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 unknown frame before headers is rejected", ClientHttp3Tests.UnknownFrameBeforeHeadersIsRejected, TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 MAX_PUSH frame on request stream is rejected", ClientHttp3Tests.MaxPushFrameOnRequestStreamIsRejected, TestTaxonomy.Http3, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 stream-level protocol error does not poison connection", ClientHttp3Tests.StreamLevelProtocolErrorDoesNotPoisonConnection, TestTaxonomy.Http3),
    Test("HTTP/3 concurrent stream reset does not leak active streams", ClientHttp3Tests.ConcurrentStreamResetDoesNotLeakActiveStreams, TestTaxonomy.Http3),
    Test("HTTP/3 QPACK decode failure does not reach route selection", ClientHttp3Tests.QpackDecodeFailureDoesNotReachRouteSelection, TestTaxonomy.Http3, TestTaxonomy.Routing, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 protocol error budget closes abusive connection", ClientHttp3Tests.ProtocolErrorBudgetClosesAbusiveConnection, TestTaxonomy.Http3),
    Test("HTTP/3 malformed pseudo headers are rejected", Sync(ClientHttp3Tests.MalformedPseudoHeadersAreRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 pseudo header after regular header is rejected", Sync(ClientHttp3Tests.PseudoHeaderAfterRegularHeaderIsRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 forbidden pseudo header is rejected", Sync(ClientHttp3Tests.ForbiddenPseudoHeaderIsRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 missing pseudo headers are rejected", Sync(ClientHttp3Tests.MissingPseudoHeadersAreRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 forbidden connection headers are rejected", Sync(ClientHttp3Tests.ForbiddenConnectionHeadersAreRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 invalid regular header name is rejected", Sync(ClientHttp3Tests.InvalidRegularHeaderNameIsRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 invalid pseudo header values are rejected", Sync(ClientHttp3Tests.InvalidPseudoHeaderValuesAreRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 malformed authority and path are rejected", Sync(ClientHttp3Tests.MalformedAuthorityAndPathAreRejected), TestTaxonomy.Http3, TestTaxonomy.Routing, TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 CONNECT pseudo header rules are enforced", Sync(ClientHttp3Tests.ConnectSpecificPseudoHeaderRulesAreEnforced), TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("HTTP/3 oversized header block is rejected", Sync(ClientHttp3Tests.OversizedHeaderBlockIsRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 QPACK header block exact boundary is accepted", Sync(ClientHttp3Tests.QpackHeaderBlockAtExactLimitIsAccepted), TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("HTTP/3 unsupported QPACK dynamic table usage is rejected", Sync(ClientHttp3Tests.UnsupportedQpackDynamicTableUsageIsRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 invalid QPACK static table reference is rejected", Sync(ClientHttp3Tests.InvalidQpackStaticTableReferenceIsRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 unsupported QPACK dynamic table prefix is rejected", Sync(ClientHttp3Tests.UnsupportedQpackDynamicTablePrefixIsRejected), TestTaxonomy.Http3, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP/3 QPACK Huffman static name reference decodes", Sync(ClientHttp3Tests.QpackHuffmanStaticNameReferenceDecodes), TestTaxonomy.Http3, TestTaxonomy.Headers),
    Test("Metrics include HTTP/3 counters", Sync(ClientHttp3Tests.MetricsIncludeHttp3Counters), TestTaxonomy.Http3, TestTaxonomy.Metrics),
    Test("Config lint reports HTTP/3 default readiness issues", Sync(ClientHttp3Tests.ConfigLintReportsHttp3DefaultReadinessIssues), TestTaxonomy.Http3, TestTaxonomy.Config),
    ];
}
