namespace MDRAVA.Tests;

internal static partial class TestRegistry
{
    private static TestCase[] AdminTlsCacheMetricsDiagnostics() =>
    [
    Test("Default admin bind is localhost-only", Sync(AdminSecurityTests.DefaultAdminBindIsLocalhostOnly), TestTaxonomy.Headers, TestTaxonomy.Admin),
    Test("Non-local admin bind without auth is rejected", Sync(AdminSecurityTests.NonLocalAdminBindWithoutAuthIsRejected), TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("Operational config rejects non-local admin URL without auth", Sync(AdminSecurityTests.OperationalConfigRejectsNonLocalAdminUrlWithoutAuth), TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("Protected admin endpoint rejects missing auth", AdminSecurityTests.ProtectedEndpointRejectsMissingAuth, TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("Protected admin endpoint rejects wrong auth", AdminSecurityTests.ProtectedEndpointRejectsWrongAuth, TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("Protected admin endpoint accepts valid bearer token", AdminSecurityTests.ProtectedEndpointAcceptsValidBearerToken, TestTaxonomy.Admin),
    Test("Known admin endpoint paths require authentication", AdminSecurityTests.KnownAdminEndpointPathsRequireAuthentication, TestTaxonomy.Routing, TestTaxonomy.Admin),
    Test("Known admin endpoint inventory matches controller routes", Sync(AdminSecurityTests.KnownAdminEndpointInventoryMatchesControllerRoutes), TestTaxonomy.Routing, TestTaxonomy.Admin),
    Test("Known admin endpoint paths accept bearer token and API key", AdminSecurityTests.KnownAdminEndpointPathsAcceptBearerAndApiKey, TestTaxonomy.Admin),
    Test("Admin auth failure response and audit do not expose presented secrets", AdminSecurityTests.AdminAuthFailureResponseAndAuditDoNotExposePresentedSecrets, TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("Admin audit capacity evicts oldest entries", Sync(AdminSecurityTests.AdminAuditCapacityEvictsOldestEntries), TestTaxonomy.Limits, TestTaxonomy.Admin),
    Test("Admin audit path omits query secrets", AdminSecurityTests.AdminAuditPathOmitsQuerySecrets, TestTaxonomy.Routing, TestTaxonomy.Admin),
    Test("Sensitive admin projections redact configured secrets", Sync(AdminSecurityTests.SensitiveProjectionRedactsConfiguredAdminSecrets), TestTaxonomy.Config, TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("Effective config does not expose admin token", Sync(AdminSecurityTests.EffectiveConfigDoesNotExposeAdminToken), TestTaxonomy.Config, TestTaxonomy.Admin, TestTaxonomy.SecurityNegativePaths),
    Test("Generated placeholder config does not contain real secret", Sync(AdminSecurityTests.GeneratedPlaceholderConfigDoesNotContainRealSecret), TestTaxonomy.Config, TestTaxonomy.Admin),
    Test("Admin audit does not log token values", AdminSecurityTests.AdminAuditDoesNotLogTokenValues, TestTaxonomy.Admin),
    Test("Manual PFX certificate behavior remains valid", AcmeTests.ManualPfxCertificateBehaviorRemainsValid, TestTaxonomy.Tls),
    Test("ACME config validation rejects missing terms acceptance", Sync(AcmeTests.AcmeConfigValidationRejectsMissingTermsAcceptance), TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("HTTP-01 challenge returns exact token response", Sync(AcmeTests.Http01ChallengeReturnsExactTokenResponse), TestTaxonomy.Tls, TestTaxonomy.Admin),
    Test("Unknown HTTP-01 challenge returns safe 404", Sync(AcmeTests.UnknownHttp01ChallengeReturnsSafe404), TestTaxonomy.Tls),
    Test("ACME renewal stores material under certs directory", AcmeTests.AcmeRenewalStoresMaterialUnderCertsDirectory, TestTaxonomy.Tls),
    Test("Loader loads stored ACME certificate on startup", AcmeTests.LoaderLoadsStoredAcmeCertificateOnStartup, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Failed ACME renewal preserves current active certificate", AcmeTests.FailedAcmeRenewalPreservesCurrentActiveCertificate, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("ACME status projection does not expose private material", AcmeTests.AcmeStatusProjectionDoesNotExposePrivateMaterial, TestTaxonomy.Config, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("ACME renewal avoids tight retry loop after failure", AcmeTests.AcmeRenewalAvoidsTightRetryLoopAfterFailure, TestTaxonomy.Tls, TestTaxonomy.RetryCircuit, TestTaxonomy.SecurityNegativePaths),
    Test("Existing HTTP upstream config remains valid", UpstreamTlsTests.ExistingHttpUpstreamConfigRemainsValid, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls),
    Test("HTTPS upstream config parses and validates", UpstreamTlsTests.HttpsUpstreamConfigParsesAndValidates, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls),
    Test("Unsupported upstream scheme is rejected", UpstreamTlsTests.UnsupportedUpstreamSchemeIsRejected, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Ambiguous upstream address is rejected", UpstreamTlsTests.AmbiguousUpstreamAddressIsRejected, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream pool key differs for HTTP and HTTPS", Sync(UpstreamTlsTests.PoolKeyDiffersForHttpAndHttps), TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls),
    Test("Upstream pool key differs for SNI and validation", Sync(UpstreamTlsTests.PoolKeyDiffersForDifferentSniAndValidation), TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls),
    Test("HTTPS upstream uses SslStream path", UpstreamTlsTests.HttpsUpstreamUsesSslStreamPath, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Routing, TestTaxonomy.Tls),
    Test("HTTPS upstream proxy forwards through TLS", UpstreamTlsTests.HttpsUpstreamProxyForwardsThroughTls, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls),
    Test("HTTPS health checks use TLS settings", UpstreamTlsTests.HttpsHealthChecksUseTlsSettings, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls, TestTaxonomy.HealthChecks),
    Test("Upstream certificate validation is enabled by default", UpstreamTlsTests.CertificateValidationIsEnabledByDefault, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls),
    Test("Explicit unsafe upstream validation projects as unsafe", UpstreamTlsTests.ExplicitUnsafeValidationModeIsProjectedAsUnsafe, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("TLS validation failure does not fall back to plaintext", UpstreamTlsTests.TlsValidationFailureDoesNotFallBackToPlaintext, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Upstream SNI override validation rejects URL port and wildcard", UpstreamTlsTests.UpstreamSniOverrideValidationRejectsUrlPortAndWildcard, TestTaxonomy.UpstreamHttp1, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Caching disabled by default", CacheTests.CachingDisabledByDefault, TestTaxonomy.Caching),
    Test("Disabled cache keeps existing proxy behavior", CacheTests.DisabledCacheKeepsExistingProxyBehavior, TestTaxonomy.Caching),
    Test("Invalid cache policy is rejected", Sync(CacheTests.InvalidCachePolicyIsRejected), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Enabled GET 200 response is stored and served", CacheTests.EnabledGet200ResponseIsStoredAndServed, TestTaxonomy.Caching),
    Test("HEAD cached response returns headers without body", CacheTests.HeadResponseReturnsHeadersWithoutBody, TestTaxonomy.Headers, TestTaxonomy.Caching),
    Test("Query string is part of cache key", Sync(CacheTests.QueryStringIsPartOfCacheKey), TestTaxonomy.Caching),
    Test("Rewrite target is part of cache key", Sync(CacheTests.RewriteTargetIsPartOfCacheKey), TestTaxonomy.Caching),
    Test("Host and vary headers affect cache key", Sync(CacheTests.HostAndVaryHeadersAffectCacheKey), TestTaxonomy.Headers, TestTaxonomy.Caching),
    Test("Authorization request is not cached by default", Sync(CacheTests.AuthorizationRequestIsNotCachedByDefault), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Cookie request is not cached by default", Sync(CacheTests.CookieRequestIsNotCachedByDefault), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Set-Cookie response is not cached by default", Sync(CacheTests.SetCookieResponseIsNotCachedByDefault), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Cache-Control no-store is not cached", Sync(CacheTests.NoStoreResponseIsNotCached), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Cache-Control no-cache is not cached", Sync(CacheTests.NoCacheResponseIsNotCached), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Cache-Control must-revalidate is not cached", Sync(CacheTests.MustRevalidateResponseIsNotCached), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Cache-Control private is not cached by default", Sync(CacheTests.PrivateResponseIsNotCachedByDefault), TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Cache-Control max-age controls TTL and expiry", Sync(CacheTests.MaxAgeControlsTtlAndExpiredEntryIsNotServed), TestTaxonomy.Caching),
    Test("Oversized response is streamed but not cached", CacheTests.OversizedResponseIsStreamedButNotCached, TestTaxonomy.Caching, TestTaxonomy.Limits, TestTaxonomy.SecurityNegativePaths),
    Test("Hop-by-hop cache headers are not stored", Sync(CacheTests.HopByHopHeadersAndTransferEncodingAreNotStored), TestTaxonomy.Headers, TestTaxonomy.Caching),
    Test("Vary header case and duplicate values affect cache key deterministically", Sync(CacheTests.VaryHeaderCaseAndDuplicateValuesAffectCacheKeyDeterministically), TestTaxonomy.Headers, TestTaxonomy.Caching),
    Test("Cache evicts oldest entries at max total bytes", Sync(CacheTests.CacheEvictsOldestEntriesAtMaxTotalBytes), TestTaxonomy.Caching),
    Test("Partial upstream response is not cached", CacheTests.PartialUpstreamResponseIsNotCached, TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Cache clear endpoint clears entries", CacheTests.CacheClearEndpointClearsEntries, TestTaxonomy.Caching),
    Test("Cache clear endpoint is protected", CacheTests.CacheClearEndpointIsProtected, TestTaxonomy.Caching),
    Test("Successful config reload clears cache", CacheTests.SuccessfulReloadClearsCache, TestTaxonomy.Caching),
    Test("Failed config reload does not clear cache", CacheTests.FailedReloadDoesNotClearCache, TestTaxonomy.Caching, TestTaxonomy.SecurityNegativePaths),
    Test("Metrics endpoint is protected by admin auth", MetricsTests.MetricsEndpointIsProtectedByAdminAuth, TestTaxonomy.Admin, TestTaxonomy.Metrics),
    Test("Metrics endpoint returns Prometheus text", Sync(MetricsTests.MetricsEndpointReturnsPrometheusText), TestTaxonomy.Metrics),
    Test("Metrics include request counters after proxied request", MetricsTests.MetricsIncludeRequestCountersAfterProxiedRequest, TestTaxonomy.Metrics),
    Test("Metrics include cache counters after cache activity", Sync(MetricsTests.MetricsIncludeCacheCountersAfterCacheActivity), TestTaxonomy.Caching, TestTaxonomy.Metrics),
    Test("Metrics include reload success and failure counters", MetricsTests.MetricsIncludeReloadCounters, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Metrics do not expose raw request details", MetricsTests.MetricsDoNotExposeRawRequestDetails, TestTaxonomy.Metrics),
    Test("Metrics failure matrix does not expose authorization cookie or query secrets", MetricsTests.MetricsFailureMatrixDoesNotExposeAuthorizationCookieOrQuerySecrets, TestTaxonomy.Admin, TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Public metrics exposure is disabled by default", Sync(MetricsTests.PublicMetricsExposureIsDisabledByDefault), TestTaxonomy.Metrics),
    Test("Invalid metrics config is rejected", Sync(MetricsTests.InvalidMetricsConfigIsRejected), TestTaxonomy.Metrics, TestTaxonomy.SecurityNegativePaths),
    Test("Metric labels are bounded and sanitized", Sync(MetricsTests.MetricLabelsAreBoundedAndSanitized), TestTaxonomy.Limits, TestTaxonomy.Metrics),
    Test("Route dry-run matches dataplane matcher", Sync(RouteDiagnosticsTests.DryRunMatchesSameRouteAsDataplaneMatcher), TestTaxonomy.Routing),
    Test("Route dry-run has no upstream I/O or retry circuit cache mutation", Sync(RouteDiagnosticsTests.DryRunDoesNotPerformUpstreamIoOrMutateRetryCircuitOrCacheState), TestTaxonomy.Routing, TestTaxonomy.Caching, TestTaxonomy.RetryCircuit),
    Test("Route dry-run reports no-match reason", Sync(RouteDiagnosticsTests.DryRunReportsNoMatchReason), TestTaxonomy.Routing),
    Test("Route dry-run reports path rewrite result", Sync(RouteDiagnosticsTests.DryRunReportsPathRewriteResult), TestTaxonomy.Routing),
    Test("Route dry-run can select HTTP/3 protocol listener", Sync(RouteDiagnosticsTests.DryRunCanSelectHttp3ProtocolListener), TestTaxonomy.Http3, TestTaxonomy.Routing),
    Test("Route dry-run reports generated route actions", Sync(RouteDiagnosticsTests.DryRunReportsGeneratedRouteActions), TestTaxonomy.Routing),
    Test("Route dry-run redacts sensitive headers", Sync(RouteDiagnosticsTests.DryRunRedactsSensitiveHeaders), TestTaxonomy.Routing, TestTaxonomy.Headers, TestTaxonomy.SecurityNegativePaths),
    Test("Config lint detects route shadowing and broad catch-all", Sync(RouteDiagnosticsTests.LintDetectsRouteShadowingAndBroadCatchAll), TestTaxonomy.Config, TestTaxonomy.Routing),
    Test("Config lint detects canonical redirect loop", Sync(RouteDiagnosticsTests.LintDetectsCanonicalRedirectLoop), TestTaxonomy.Config, TestTaxonomy.Routing),
    Test("Config lint detects HTTPS redirect without HTTPS listener", Sync(RouteDiagnosticsTests.LintDetectsHttpsRedirectWithoutHttpsListener), TestTaxonomy.Config, TestTaxonomy.Routing, TestTaxonomy.Tls),
    Test("Config lint warns about unsafe upstream TLS validation", Sync(RouteDiagnosticsTests.LintWarnsAboutUnsafeUpstreamTlsValidation), TestTaxonomy.UpstreamHttp1, TestTaxonomy.Config, TestTaxonomy.Routing, TestTaxonomy.Tls, TestTaxonomy.SecurityNegativePaths),
    Test("Config lint omits resolved upstream HTTP/3 pooling limitation", Sync(RouteDiagnosticsTests.LintDoesNotReportResolvedUpstreamHttp3PoolingLimitation), TestTaxonomy.Http3, TestTaxonomy.Config, TestTaxonomy.Routing, TestTaxonomy.Limits),
    Test("Config lint handles JSON and YAML submitted config without applying", Sync(RouteDiagnosticsTests.LintHandlesJsonAndYamlSubmittedConfigWithoutApplying), TestTaxonomy.Config, TestTaxonomy.Routing),
    Test("Config lint output has stable codes and severities", Sync(RouteDiagnosticsTests.LintOutputHasStableCodesAndSeverities), TestTaxonomy.Config, TestTaxonomy.Routing),
    Test("Diagnostic endpoints require admin auth", RouteDiagnosticsTests.DiagnosticEndpointsRequireAdminAuth, TestTaxonomy.Routing, TestTaxonomy.Admin, TestTaxonomy.Metrics),
    Test("Metrics include lint and route dry-run counters", Sync(RouteDiagnosticsTests.MetricsIncludeLintAndRouteDryRunCounters), TestTaxonomy.Routing, TestTaxonomy.Metrics),
    Test("Route-only reload does not rebind unchanged listener", ListenerRebindingTests.RouteOnlyReloadDoesNotRebindUnchangedListener, TestTaxonomy.Config, TestTaxonomy.Routing),
    Test("Adding listener starts only new listener", ListenerRebindingTests.AddingListenerStartsOnlyNewListener, TestTaxonomy.Config),
    Test("Removing listener stops accepting new connections", ListenerRebindingTests.RemovingListenerStopsAcceptingNewConnections, TestTaxonomy.Config),
    Test("Changed listener is replaced safely", ListenerRebindingTests.ChangedListenerIsReplacedSafely, TestTaxonomy.Config),
    Test("Failed new listener start preserves old active listener", ListenerRebindingTests.FailedNewListenerStartPreservesOldActiveListener, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Failed config reload preserves old active listeners", ListenerRebindingTests.FailedConfigReloadPreservesOldActiveListeners, TestTaxonomy.Config, TestTaxonomy.SecurityNegativePaths),
    Test("Certificate-only update does not rebind listener", ListenerRebindingTests.CertificateOnlyUpdateDoesNotRebindListener, TestTaxonomy.Config, TestTaxonomy.Tls),
    Test("Admin bind is not affected by proxy listener reload", ListenerRebindingTests.AdminBindIsNotAffectedByProxyListenerReload, TestTaxonomy.Config, TestTaxonomy.Admin),
    Test("Reload diagnostics report listener diff", ListenerRebindingTests.ReloadDiagnosticsReportListenerDiff, TestTaxonomy.Config, TestTaxonomy.Metrics),
    Test("Metrics count listener reload outcomes", ListenerRebindingTests.MetricsCountListenerReloadOutcomes, TestTaxonomy.Config, TestTaxonomy.Metrics),
    ];
}
