using BusinessProxyMetricsSnapshot = MDRAVA.BLL.ControlPlane.Metrics.ProxyMetricsSnapshot;

namespace MDRAVA.API.Controllers;

public sealed record ProxyMetricsSnapshotResponse(
    long AcceptedConnections,
    long ActiveConnections,
    long TotalRequests,
    long UpstreamSuccesses,
    long UpstreamFailures,
    long BytesRead,
    long BytesWritten,
    long ParseErrors,
    long RejectedMalformedRequests,
    long RejectedUnsupportedRequestFraming,
    long UpstreamMalformedResponses,
    long ClientBodyRelayFailures,
    long UpstreamBodyRelayFailures,
    long ClientRequestHeadTimeouts,
    long ClientRequestBodyTimeouts,
    long UpstreamConnectFailures,
    long UpstreamConnectTimeouts,
    long UpstreamResponseHeadTimeouts,
    long UpstreamResponseBodyTimeouts,
    long UpstreamPrematureDisconnects,
    long ClientPrematureDisconnects,
    long ProxyGenerated502Responses,
    long ProxyGenerated504Responses,
    long DownstreamWriteTimeouts,
    long TlsHandshakeAttempts,
    long TlsHandshakeSuccesses,
    long TlsHandshakeFailures,
    long TlsHandshakeTimeouts,
    long TlsNoCertificateForSniFailures,
    long ClientConnectionsClosedByIdleTimeout,
    long ClientConnectionsClosedByMaxRequests,
    long UpstreamConnectionsOpened,
    long UpstreamConnectionsReused,
    long UpstreamConnectionsDiscarded,
    long UpstreamPoolIdleConnections,
    long UpstreamPoolActiveConnections,
    long UpgradeRequestsReceived,
    long UpgradeRequestsSucceeded,
    long UpgradeRequestsRejected,
    long UpgradeUpstreamFailures,
    long ActiveTunnels,
    long TotalTunnels,
    long TunnelIdleTimeouts,
    long TunnelBytesClientToUpstream,
    long TunnelBytesUpstreamToClient,
    long TunnelRelayFailures,
    long UpstreamSelections,
    long NoHealthyUpstreamFailures,
    long HealthChecksAttempted,
    long HealthChecksSucceeded,
    long HealthChecksFailed,
    long UpstreamHealthTransitions,
    long UpstreamRequestFailures,
    long RequestIdsGenerated,
    long AccessLogsEmitted,
    long RecentDiagnosticsOverwritten,
    long ConnectionAdmissionRejections,
    long ActiveTlsHandshakes,
    long TlsHandshakeAdmissionRejections,
    long RateLimitedRequests,
    long RateLimitedUpgrades,
    long RequestBodySizeRejections,
    long ParserLimitRejections,
    IReadOnlyDictionary<string, long> RequestFailuresByKind,
    IReadOnlyList<ProxyRequestSeriesSnapshotResponse> RequestsByRoute,
    long ConfigReloadSuccesses,
    long ConfigReloadFailures,
    long AdminAuthSuccesses,
    long AdminAuthFailures,
    long AcmeRenewalAttempts,
    long AcmeRenewalSuccesses,
    long AcmeRenewalFailures,
    long RetryAttempts,
    long RetryExhausted,
    IReadOnlyList<ProxyRetrySkippedSnapshotResponse> RetrySkipped,
    long CircuitOpened,
    long CircuitHalfOpened,
    long CircuitClosed,
    long CircuitRejections,
    long NoAvailableUpstreamFailures,
    IReadOnlyList<ProxyUpstreamSelectionSnapshotResponse> UpstreamSelectionsByUpstream,
    long ListenerReloadAttempts,
    long ListenerReloadSuccesses,
    long ListenerReloadFailures,
    long ListenerReloadAdded,
    long ListenerReloadRemoved,
    long ListenerReloadChanged,
    long ListenerReloadUnchanged,
    long ListenerStartFailures,
    long ListenerDrainCount,
    long ActiveListeners,
    long Http2AcceptedConnections,
    long Http2Requests,
    long ActiveHttp2Streams,
    IReadOnlyDictionary<string, long> Http2ProtocolErrors,
    long UpstreamHttp2Requests,
    long UpstreamHttp2AlpnFailures,
    long UpstreamHttp2ProtocolErrors,
    long UpstreamHttp3Requests,
    long UpstreamHttp3ConnectionAttempts,
    long UpstreamHttp3ConnectionSuccesses,
    long UpstreamHttp3ConnectionFailures,
    long UpstreamHttp3PoolConnectionsOpened,
    long UpstreamHttp3PoolConnectionsReused,
    long UpstreamHttp3PoolConnectionsClosed,
    long UpstreamHttp3StreamLimitRejections,
    long ActiveUpstreamHttp3Connections,
    long ActiveUpstreamHttp3Streams,
    IReadOnlyDictionary<string, long> UpstreamHttp3ProtocolErrors,
    long Http3AcceptedConnections,
    long ActiveHttp3Connections,
    long Http3Requests,
    long Http3ProxiedRequests,
    long Http3GeneratedResponses,
    long ActiveHttp3Streams,
    long Http3StreamResets,
    long Http3StreamedResponses,
    long ActiveHttp3ResponseStreams,
    long Http3ResponseBytesSent,
    long Http3RequestBodyBytesReceived,
    long Http3ResponseStreamResets,
    long Http3AltSvcEmitted,
    long Http3AltSvcSuppressed,
    IReadOnlyList<ProxyHttp3RequestOutcomeSnapshotResponse> Http3RequestsByOutcome,
    IReadOnlyDictionary<string, long> Http3RejectedRequests,
    IReadOnlyDictionary<string, long> Http3ProtocolErrors,
    long QuicListenerStartSuccesses,
    long QuicListenerStartFailures,
    long ActiveQuicListeners,
    long ConfigLintRuns,
    IReadOnlyList<ProxyConfigLintFindingMetricSnapshotResponse> ConfigLintFindings,
    long RouteMatchDryRuns,
    IReadOnlyList<ProxyRouteDryRunFailureSnapshotResponse> RouteMatchDryRunFailures)
{
    public static ProxyMetricsSnapshotResponse FromSnapshot(BusinessProxyMetricsSnapshot snapshot)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        var http3 = snapshot.Http3;
        var listeners = snapshot.Listeners;
        var upstreamHttp3 = snapshot.UpstreamHttp3;

        return new ProxyMetricsSnapshotResponse(
            snapshot.AcceptedConnections,
            snapshot.ActiveConnections,
            snapshot.TotalRequests,
            snapshot.UpstreamSuccesses,
            snapshot.UpstreamFailures,
            snapshot.BytesRead,
            snapshot.BytesWritten,
            snapshot.ParseErrors,
            snapshot.RejectedMalformedRequests,
            snapshot.RejectedUnsupportedRequestFraming,
            snapshot.UpstreamMalformedResponses,
            snapshot.ClientBodyRelayFailures,
            snapshot.UpstreamBodyRelayFailures,
            snapshot.ClientRequestHeadTimeouts,
            snapshot.ClientRequestBodyTimeouts,
            snapshot.UpstreamConnectFailures,
            snapshot.UpstreamConnectTimeouts,
            snapshot.UpstreamResponseHeadTimeouts,
            snapshot.UpstreamResponseBodyTimeouts,
            snapshot.UpstreamPrematureDisconnects,
            snapshot.ClientPrematureDisconnects,
            snapshot.ProxyGenerated502Responses,
            snapshot.ProxyGenerated504Responses,
            snapshot.DownstreamWriteTimeouts,
            snapshot.TlsHandshakeAttempts,
            snapshot.TlsHandshakeSuccesses,
            snapshot.TlsHandshakeFailures,
            snapshot.TlsHandshakeTimeouts,
            snapshot.TlsNoCertificateForSniFailures,
            snapshot.ClientConnectionsClosedByIdleTimeout,
            snapshot.ClientConnectionsClosedByMaxRequests,
            snapshot.UpstreamConnectionsOpened,
            snapshot.UpstreamConnectionsReused,
            snapshot.UpstreamConnectionsDiscarded,
            snapshot.UpstreamPoolIdleConnections,
            snapshot.UpstreamPoolActiveConnections,
            snapshot.UpgradeRequestsReceived,
            snapshot.UpgradeRequestsSucceeded,
            snapshot.UpgradeRequestsRejected,
            snapshot.UpgradeUpstreamFailures,
            snapshot.ActiveTunnels,
            snapshot.TotalTunnels,
            snapshot.TunnelIdleTimeouts,
            snapshot.TunnelBytesClientToUpstream,
            snapshot.TunnelBytesUpstreamToClient,
            snapshot.TunnelRelayFailures,
            snapshot.UpstreamSelections,
            snapshot.NoHealthyUpstreamFailures,
            snapshot.HealthChecksAttempted,
            snapshot.HealthChecksSucceeded,
            snapshot.HealthChecksFailed,
            snapshot.UpstreamHealthTransitions,
            snapshot.UpstreamRequestFailures,
            snapshot.RequestIdsGenerated,
            snapshot.AccessLogsEmitted,
            snapshot.RecentDiagnosticsOverwritten,
            snapshot.ConnectionAdmissionRejections,
            snapshot.ActiveTlsHandshakes,
            snapshot.TlsHandshakeAdmissionRejections,
            snapshot.RateLimitedRequests,
            snapshot.RateLimitedUpgrades,
            snapshot.RequestBodySizeRejections,
            snapshot.ParserLimitRejections,
            new Dictionary<string, long>(snapshot.RequestFailuresByKind),
            ProxyRequestSeriesSnapshotResponse.FromSnapshots(snapshot.RequestsByRoute),
            snapshot.ConfigReloadSuccesses,
            snapshot.ConfigReloadFailures,
            snapshot.AdminAuthSuccesses,
            snapshot.AdminAuthFailures,
            snapshot.AcmeRenewalAttempts,
            snapshot.AcmeRenewalSuccesses,
            snapshot.AcmeRenewalFailures,
            snapshot.RetryAttempts,
            snapshot.RetryExhausted,
            ProxyRetrySkippedSnapshotResponse.FromSnapshots(snapshot.RetrySkipped),
            snapshot.CircuitOpened,
            snapshot.CircuitHalfOpened,
            snapshot.CircuitClosed,
            snapshot.CircuitRejections,
            snapshot.NoAvailableUpstreamFailures,
            ProxyUpstreamSelectionSnapshotResponse.FromSnapshots(snapshot.UpstreamSelectionsByUpstream),
            listeners.ReloadAttempts,
            listeners.ReloadSuccesses,
            listeners.ReloadFailures,
            listeners.ReloadAdded,
            listeners.ReloadRemoved,
            listeners.ReloadChanged,
            listeners.ReloadUnchanged,
            listeners.StartFailures,
            listeners.Drains,
            listeners.ActiveListeners,
            snapshot.Http2AcceptedConnections,
            snapshot.Http2Requests,
            snapshot.ActiveHttp2Streams,
            new Dictionary<string, long>(snapshot.Http2ProtocolErrors),
            snapshot.UpstreamHttp2Requests,
            snapshot.UpstreamHttp2AlpnFailures,
            snapshot.UpstreamHttp2ProtocolErrors,
            upstreamHttp3.Requests,
            upstreamHttp3.ConnectionAttempts,
            upstreamHttp3.ConnectionSuccesses,
            upstreamHttp3.ConnectionFailures,
            upstreamHttp3.PoolConnectionsOpened,
            upstreamHttp3.PoolConnectionsReused,
            upstreamHttp3.PoolConnectionsClosed,
            upstreamHttp3.StreamLimitRejections,
            upstreamHttp3.ActiveConnections,
            upstreamHttp3.ActiveStreams,
            new Dictionary<string, long>(upstreamHttp3.ProtocolErrors),
            http3.AcceptedConnections,
            http3.ActiveConnections,
            http3.Requests,
            http3.ProxiedRequests,
            http3.GeneratedResponses,
            http3.ActiveStreams,
            http3.StreamResets,
            http3.StreamedResponses,
            http3.ActiveResponseStreams,
            http3.ResponseBytesSent,
            http3.RequestBodyBytesReceived,
            http3.ResponseStreamResets,
            http3.AltSvcEmitted,
            http3.AltSvcSuppressed,
            ProxyHttp3RequestOutcomeSnapshotResponse.FromSnapshots(http3.RequestsByOutcome),
            new Dictionary<string, long>(http3.RejectedRequests),
            new Dictionary<string, long>(http3.ProtocolErrors),
            http3.QuicListenerStartSuccesses,
            http3.QuicListenerStartFailures,
            http3.ActiveQuicListeners,
            snapshot.ConfigLintRuns,
            ProxyConfigLintFindingMetricSnapshotResponse.FromSnapshots(snapshot.ConfigLintFindings),
            snapshot.RouteMatchDryRuns,
            ProxyRouteDryRunFailureSnapshotResponse.FromSnapshots(snapshot.RouteMatchDryRunFailures));
    }
}
